<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '(לא הוגדר)',
    'An internal server error occurred.' => 'שגיאת שרת פנימית',
    'Delete' => 'מחק',
    'Error' => 'שגיאה',
    'File upload failed.' => 'העלאת קובץ נכשלה',
    'Home' => 'דף הבית',
    'Invalid data received for parameter "{param}".' => 'התקבל ערך לא חוקי לפרמטר "{param}"',
    'Login Required' => 'נדרשת הרשמה',
    'Missing required arguments: {params}' => 'חסרים ארגומנטים נדרשים: {params}',
    'Missing required parameters: {params}' => 'חסרים פרמטרים נדרשים: {params}',
    'No' => 'לא',
    'No help for unknown command "{command}".' => 'פקודה "{command}" לא מוכרת ואין לה עזרה',
    'No help for unknown sub-command "{command}".' => 'תת-פקודה "{command}" לא מוכרת ואין לה עזרה',
    'No results found.' => 'לא נמצאו תוצאות',
    'Only files with these extensions are allowed: {extensions}.' => 'רק קבצים עם ההרחבות הבאות מותרים: {extentions}.',
    'Page not found.' => 'דף לא נמצא',
    'Please fix the following errors:' => 'בבקשה, תקן את השגיאות הבאות: ',
    'Please upload a file.' => 'נא העלה קובץ.',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.' => 'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.لات}}.',
    'The file "{file}" is not an image.' => 'הקובץ "{file}" אינו קובץ תמונה.',
    'The file "{file}" is too big. Its size cannot exceed {limit, number} {limit, plural, one{byte} other{bytes}}.' => 'הקובץ "{file}" גדול מדי. גודל זה אינו מצליח {limit, number} {limit, plural, one{byte} other{bytes}}.',
    'The file "{file}" is too small. Its size cannot be smaller than {limit, number} {limit, plural, one{byte} other{bytes}}.' => 'הקובץ "{file}" קטן מדי. הקובץ אינו יכול להיות קטן מ {limit, number} {limit, plural, one{byte} other{bytes}}.',
    'The format of {attribute} is invalid.' => 'הפורמט של {attribute} אינו חוקי.',
    'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'התמונה "{file}" גדולה מדי. הגובה לא יכול להיות גדול מ {limit, number} {limit, plural, one{pixel} other{pixels}}.',
    'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'התמונה "{file}" גדולה מדי. הגובה לא יכול להיות גדול מ {limit, number} {limit, plural, one{pixel} other{pixels}}.',
    'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'الصورة "{file}" صغيرة جداً. ارتفاعها لا يمكن أن يقل عن  {limit, number} {limit, plural, other{بكسل}}.',
    'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'الصورة "{file}" كبيرة جداً. عرضها لا يمكن أن يقل عن  {limit, number} {limit, plural, other{بكسل}}.',
    'The verification code is incorrect.' => 'رمز التحقق غير صحيح',
    'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.' => 'مجموع <b>{count, number}</b> {count, plural, one{مُدخل} few{مُدخلات} many{مُدخل}}.',
    'Unable to verify your data submission.' => 'لم نستطع التأكد من البيانات المقدمة.',
    'Unknown command "{command}".' => 'Unknown command "{command}".',
    'Unknown option: --{name}' => 'Unknown option: --{name}',
    'Update' => 'Update',
    'View' => 'View',
    'Yes' => 'כן',
    'You are not allowed to perform this action.' => 'غير مصرح لك القيام بهذا العمل',
    'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.' => 'تستطيع كأقصى حد تحميل {limit, number} {limit, plural, one{ملف} few{ملفات} many{ملف} other{ملفات}}.',
    'the input value' => 'قيمة المُدخل',
    '{attribute} "{value}" has already been taken.' => '{attribute} "{value}" כבר בשימוש',
    '{attribute} cannot be blank.' => '{attribute} לא יכול להיות ריק.',
    '{attribute} is invalid.' => '{attribute} לא חוקי.',
    '{attribute} is not a valid URL.' => '{attribute} איננו כתובת אינטרנט חוקית.',
    '{attribute} is not a valid email address.' => '{attribute} לא כתובת מייל חוקית.',
    '{attribute} must be "{requiredValue}".' => '{attribute} חייב להיות "{requiredValue}".',
    '{attribute} must be a number.' => '{attribute} חייב להיות מספר',
    '{attribute} must be a string.' => '{attribute} חייב להיות מחרוזת טקסט',
    '{attribute} must be an integer.' => '{attribute} חייב להיות מספר שלם',
    '{attribute} must be either "{true}" or "{false}".' => '{attribute} חייב להיות "{true}" או "{false}".',
    '{attribute} must be greater than "{compareValue}".' => '{attribute} يجب أن يكون أكبر من "{compareValue}".',
    '{attribute} must be greater than or equal to "{compareValue}".' => '{attribute} يجب أن يكون أكبر من أو يساوي  "{compareValue}".',
    '{attribute} must be less than "{compareValue}".' => '{attribute} يجب أن يكون أصغر من "{compareValue}".',
    '{attribute} must be less than or equal to "{compareValue}".' => '{attribute} يجب أن يكون أصغر من أو يساوي "{compareValue}".',
    '{attribute} must be no greater than {max}.' => '{attribute} يجب أن لا يكون أكبر من "{compareValue}".',
    '{attribute} must be no less than {min}.' => '{attribute} يجب أن لا يكون أصغر من "{min}".',
    '{attribute} must be repeated exactly.' => '{attribute} يجب أن يكون متطابق.',
    '{attribute} must not be equal to "{compareValue}".' => '{attribute} חייב להיות שווה ל "{compareValue}"',
    '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => '{attribute} אמור לכלול לפחות {min, number} {min, plural, one{حرف} few{حروف} many{حرف}}.',
    '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.' => '{attribute} אמור לא לכלול יותר מ {max, number} {max, plural, one{حرف} few{حروف} many{حرف}}.',
    '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => '{attribute}  אמור לכלול {length, number} {length, plural, one{حرف} few{حروف} many{حرف}}.',
];
