<?php
/**
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '(לא הוגדר)',
    'An internal server error occurred.' => 'שגיאת שרת פנימית',
    'Are you sure you want to delete this item?' => 'האם אתה בטוח שברצונך למחוק פריט זה?',
    'Delete' => 'מחק',
    'Error' => 'שגיאה',
    'File upload failed.' => 'העלאת קובץ נכשלה',
    'Home' => 'דף הבית',
    'Invalid data received for parameter "{param}".' => 'התקבל ערך לא חוקי לפרמטר "{param}"',
    'Login Required' => 'נדרשת הרשמה',
    'Missing required arguments: {params}' => 'חסרים ארגומנטים נדרשים: {params}',
    'Missing required parameters: {params}' => 'חסרים פרמטרים נדרשים: {params}',
    'No' => 'לא',
    'No help for unknown command "{command}".' => 'פקודה "{command}" לא מוכרת ואין לה עזרה',
    'No help for unknown sub-command "{command}".' => 'תת-פקודה "{command}" לא מוכרת ואין לה עזרה',
    'No results found.' => 'לא נמצאו תוצאות',
    'Only files with these extensions are allowed: {extensions}.' => 'רק קבצים עם ההרחבות הבאות מותרים: {extensions}.',
    'Page not found.' => 'דף לא נמצא',
    'Please fix the following errors:' => 'בבקשה, תקן את השגיאות הבאות: ',
    'Please upload a file.' => 'נא העלה קובץ.',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.' => 'מציג <b>{begin, number}-{end, number}</b> מתוך <b>{totalCount, number}</b> {totalCount, plural, one{רשומה} other{רשומות}}.',
    'The file "{file}" is not an image.' => 'הקובץ "{file}" אינו קובץ תמונה.',
    'The file "{file}" is too big. Its size cannot exceed {formattedLimit}.' => 'הקובץ "{file}" גדול מדי. גודל זה אינו מצליח {formattedLimit}.',
    'The file "{file}" is too small. Its size cannot be smaller than {formattedLimit}.' => 'הקובץ "{file}" קטן מדי. הקובץ אינו יכול להיות קטן מ {formattedLimit}.',
    'The format of {attribute} is invalid.' => 'הפורמט של {attribute} אינו חוקי.',
    'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'התמונה "{file}" גדולה מדי. הגובה לא יכול להיות גדול מ {limit, number} {limit, plural, one{pixel} other{pixels}}.',
    'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'התמונה "{file}" גדולה מדי. הרוחב לא יכול להיות גדול מ {limit, number} {limit, plural, one{pixel} other{pixels}}.',
    'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'התמונה "{file}" קטנה מדי. הגובה לא יכול להיות קטן מ {limit, number} {limit, plural, one{pixel} other{pixels}}.',
    'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'התמונה "{file}" קטנה מדי. הרוחב לא יכול להיות קטן מ {limit, number} {limit, plural, one{pixel} other{pixels}}.',
    'The verification code is incorrect.' => 'קוד האימות אינו תקין.',
    'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.' => 'סך הכל <b>{count, number}</b> {count, plural, one{אייטם} other{אייטמים}}.',
    'Unable to verify your data submission.' => 'אין אפשרות לאמת את המידע שהתקבל.',
    'Unknown command "{command}".' => 'Unknown command "{command}".',
    'Unknown option: --{name}' => 'Unknown option: --{name}',
    'Update' => 'עדכון',
    'View' => 'תצוגה',
    'Yes' => 'כן',
    'You are not allowed to perform this action.' => 'אינך מורשה לבצע את הפעולה הזו.',
    'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.' => 'אתה יכול להעלות לכל היותר {limit, number} {limit, plural, one{קובץ} other{קבצים}}.',
    'the input value' => 'הערך המוכנס',
    '{attribute} "{value}" has already been taken.' => '{attribute} "{value}" כבר בשימוש',
    '{attribute} cannot be blank.' => '{attribute} לא יכול להיות ריק.',
    '{attribute} is invalid.' => '{attribute} לא חוקי.',
    '{attribute} is not a valid URL.' => '{attribute} איננו כתובת אינטרנט חוקית.',
    '{attribute} is not a valid email address.' => '{attribute} לא כתובת מייל חוקית.',
    '{attribute} must be "{requiredValue}".' => '{attribute} חייב להיות "{requiredValue}".',
    '{attribute} must be a number.' => '{attribute} חייב להיות מספר',
    '{attribute} must be a string.' => '{attribute} חייב להיות מחרוזת טקסט',
    '{attribute} must be an integer.' => '{attribute} חייב להיות מספר שלם',
    '{attribute} must be either "{true}" or "{false}".' => '{attribute} חייב להיות "{true}" או "{false}".',
    '{attribute} must be greater than "{compareValue}".' => '{attribute} חייב להיות גדול מ "{compareValue}".',
    '{attribute} must be greater than or equal to "{compareValue}".' => '{attribute} חייב להיות גדול מ או שווה  "{compareValue}".',
    '{attribute} must be less than "{compareValue}".' => '{attribute} חייב להיות פחות מ "{compareValue}".',
    '{attribute} must be less than or equal to "{compareValue}".' => '{attribute} חייב להיות פחות מ או שווה "{compareValue}".',
    '{attribute} must be no greater than {max}.' => '{attribute} חייב להיות לא יותר מ "{max}".',
    '{attribute} must be no less than {min}.' => '{attribute} חייב להיות לא פחות מ "{min}".',
    '{attribute} must be repeated exactly.' => '{attribute} חייב להיות מוחזר בדיוק.',
    '{attribute} must not be equal to "{compareValue}".' => '{attribute} חייב להיות שווה ל "{compareValue}"',
    '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => '{attribute} אמור לכלול לפחות {min, number} {min, plural, one{תו} other{תוים}}.',
    '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.' => '{attribute} אמור לא לכלול יותר מ{max, number} {max, plural, one{תו} other{תוים}}.',
    '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => '{attribute}  אמור לכלול {length, number} {length, plural, one{תו} other{תוים}}.',
];
