<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{attribute} must be equal to "{compareValueOrAttribute}".' => 'Значення "{attribute}" повинно бути рівним "{compareValueOrAttribute}".',
    '{attribute} must be greater than "{compareValueOrAttribute}".' => 'Значення "{attribute}" повинно бути більшим значення "{compareValueOrAttribute}".',
    '{attribute} must be greater than or equal to "{compareValueOrAttribute}".' => 'Значення "{attribute}" повинно бути більшим або дорівнювати значенню "{compareValueOrAttribute}".',
    '{attribute} must be less than "{compareValueOrAttribute}".' => 'Значення "{attribute}" повинно бути меншим значення "{compareValueOrAttribute}".',
    '{attribute} must be less than or equal to "{compareValueOrAttribute}".' => 'Значення "{attribute}" повинно бути меншим або дорівнювати значенню "{compareValueOrAttribute}".',
    '{attribute} must not be equal to "{compareValueOrAttribute}".' => 'Значення "{attribute}" не повинно бути рівним "{compareValueOrAttribute}".',
    '(not set)' => '(не задано)',
    'An internal server error occurred.' => 'Виникла внутрішня помилка сервера.',
    'Are you sure you want to delete this item?' => 'Ви впевнені, що хочете видалити цей елемент?',
    'Delete' => 'Видалити',
    'Error' => 'Помилка',
    'File upload failed.' => 'Завантаження файлу не вдалося.',
    'Home' => 'Головна',
    'Invalid data received for parameter "{param}".' => 'Отримано невірне значення для параметра "{param}".',
    'Login Required' => 'Необхідно увійти',
    'Missing required arguments: {params}' => 'Відсутні обовʼязкові аргументи: {params}',
    'Missing required parameters: {params}' => 'Відсутні обовʼязкові параметри: {params}',
    'No' => 'Ні',
    'No results found.' => 'Нічого не знайдено.',
    'Only files with these MIME types are allowed: {mimeTypes}.' => 'Дозволені файли лише з наступними MIME-типами: {mimeTypes}.',
    'Only files with these extensions are allowed: {extensions}.' => 'Дозволені файли лише з наступними розширеннями: {extensions}.',
    'Page not found.' => 'Сторінка не знайдена.',
    'Please fix the following errors:' => 'Будь ласка, виправте наступні помилки:',
    'Please upload a file.' => 'Будь ласка, завантажте файл.',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.' => 'Показані <b>{begin, number}-{end, number}</b> із <b>{totalCount, number}</b> {totalCount, plural, one{запису} other{записів}}.',
    'The file "{file}" is not an image.' => 'Файл "{file}" не є зображенням.',
    'The file "{file}" is too big. Its size cannot exceed {formattedLimit}.' => 'Файл "{file}" занадто великий. Розмір не повинен перевищувати {formattedLimit}.',
    'The file "{file}" is too small. Its size cannot be smaller than {formattedLimit}.' => 'Файл "{file}" занадто малий. Розмір повинен бути більше, ніж {formattedLimit}.',
    'The format of {attribute} is invalid.' => 'Невірний формат значення "{attribute}".',
    'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Зображення "{file}" занадто велике. Висота не повинна перевищувати {limit, number} {limit, plural, one{піксель} few{пікселя} many{пікселів} other{пікселя}}.',
    'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Зображення "{file}" занадто велике. Ширина не повинна перевищувати {limit, number} {limit, plural, one{піксель} few{пікселя} many{пікселів} other{пікселя}}.',
    'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Зображення "{file}" занадто мале. Висота повинна бути більше, ніж {limit, number} {limit, plural, one{піксель} few{пікселя} many{пікселів} other{пікселя}}.',
    'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Зображення "{file}" занадто мале. Ширина повинна бути більше, ніж {limit, number} {limit, plural, one{піксель} few{пікселя} many{пікселів} other{пікселя}}.',
    'The requested view "{name}" was not found.' => 'Представлення "{name}" не знайдено.',
    'The verification code is incorrect.' => 'Невірний код перевірки.',
    'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.' => 'Всього <b>{count, number}</b> {count, plural, one{запис} few{записи} many{записів} other{записи}}.',
    'Unable to verify your data submission.' => 'Не вдалося перевірити передані дані.',
    'Unknown option: --{name}' => 'Невідома опція : --{name}',
    'Update' => 'Оновити',
    'View' => 'Переглянути',
    'Yes' => 'Так',
    'You are not allowed to perform this action.' => 'Вам не дозволено виконувати дану дію.',
    'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.' => 'Ви не можете завантажувати більше {limit, number} {limit, plural, one{файла} few{файлів} many{файлів} other{файла}}.',
    'in {delta, plural, =1{a day} other{# days}}' => 'через {delta, plural, =1{день} one{# день} few{# дні} many{# днів} other{# дні}}',
    'in {delta, plural, =1{a minute} other{# minutes}}' => 'через {delta, plural, =1{хвилину} one{# хвилину} few{# хвилини} many{# хвилин} other{# хвилини}}',
    'in {delta, plural, =1{a month} other{# months}}' => 'через {delta, plural, =1{місяць} one{# місяць} few{# місяці} many{# місяців} other{# місяці}}',
    'in {delta, plural, =1{a second} other{# seconds}}' => 'через {delta, plural, =1{секунду} one{# секунду} few{# секунди} many{# секунд} other{# секунди}}',
    'in {delta, plural, =1{a year} other{# years}}' => 'через {delta, plural, =1{рік} one{# рік} few{# роки} many{# років} other{# роки}}',
    'in {delta, plural, =1{an hour} other{# hours}}' => 'через {delta, plural, =1{годину} one{# годину} few{# години} many{# годин} other{# години}}',
    'just now' => 'саме зараз',
    'the input value' => 'введене значення',
    '{attribute} "{value}" has already been taken.' => 'Значення «{value}» для «{attribute}» вже зайнято.',
    '{attribute} cannot be blank.' => 'Необхідно заповнити "{attribute}".',
    '{attribute} contains wrong subnet mask.' => 'Значення «{attribute}» містить неправильну маску підмережі.',
    '{attribute} is invalid.' => 'Значення "{attribute}" не вірне.',
    '{attribute} is not a valid URL.' => 'Значення "{attribute}" не є правильним URL.',
    '{attribute} is not a valid email address.' => 'Значення "{attribute}" не є правильною email адресою.',
    '{attribute} is not in the allowed range.' => 'Значення «{attribute}» не входить в список дозволених діапазонів адрес.',
    '{attribute} must be "{requiredValue}".' => 'Значення "{attribute}" має бути рівним "{requiredValue}".',
    '{attribute} must be a number.' => 'Значення "{attribute}" має бути числом.',
    '{attribute} must be a string.' => 'Значення "{attribute}" має бути текстовим рядком.',
    '{attribute} must be a valid IP address.' => 'Значення «{attribute}» повинно бути правильною IP адресою.',
    '{attribute} must be an IP address with specified subnet.' => 'Значення «{attribute}» повинно бути IP адресою з підмережею.',
    '{attribute} must be an integer.' => 'Значення "{attribute}" має бути цілим числом.',
    '{attribute} must be either "{true}" or "{false}".' => 'Значення "{attribute}" має дорівнювати "{true}" або "{false}".',
    '{attribute} must be no greater than {max}.' => 'Значення "{attribute}" не повинно перевищувати {max}.',
    '{attribute} must be no less than {min}.' => 'Значення "{attribute}" має бути більшим {min}.',
    '{attribute} must not be a subnet.' => 'Значення «{attribute}» не повинно бути підмережею.',
    '{attribute} must not be an IPv4 address.' => 'Значення «{attribute}» не повинно бути IPv4 адресою.',
    '{attribute} must not be an IPv6 address.' => 'Значення «{attribute}» не повинно бути IPv6 адресою.',
    '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => 'Значення "{attribute}" повинно містити мінімум {min, number} {min, plural, one{символ} few{символа} many{символів} other{символа}}.',
    '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.' => 'Значення "{attribute}" повинно містити максимум {max, number} {max, plural, one{символ} few{символа} many{символів} other{символа}}.',
    '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => 'Значення "{attribute}" повинно містити {length, number} {length, plural, one{символ} few{символа} many{символів} other{символа}}.',
    '{delta, plural, =1{1 day} other{# days}}' => '{delta, plural, one{# день} few{# дні} many{# днів} other{# днів}}',
    '{delta, plural, =1{1 hour} other{# hours}}' => '{delta, plural, one{# година} few{# години} many{# годин} other{# годин}}',
    '{delta, plural, =1{1 minute} other{# minutes}}' => '{delta, plural, one{# хвилина} few{# хвилини} many{# хвилин} other{# хвилин}}',
    '{delta, plural, =1{1 month} other{# months}}' => '{delta, plural, one{# місяць} few{# місяця} many{# місяців} other{# місяців}}',
    '{delta, plural, =1{1 second} other{# seconds}}' => '{delta, plural, one{# секунда} few{# секунди} many{# секунд} other{# секунд}}',
    '{delta, plural, =1{1 year} other{# years}}' => '{delta, plural, one{# рік} few{# роки} many{# років} other{# років}}',
    '{delta, plural, =1{a day} other{# days}} ago' => '{delta, plural, =1{день} one{# день} few{# дні} many{# днів} other{# дні}} тому',
    '{delta, plural, =1{a minute} other{# minutes}} ago' => '{delta, plural, =1{хвилину} one{# хвилину} few{# хвилини} many{# хвилин} other{# хвилини}} тому',
    '{delta, plural, =1{a month} other{# months}} ago' => '{delta, plural, =1{місяць} one{# місяць} few{# місяці} many{# місяців} other{# місяці}} тому',
    '{delta, plural, =1{a second} other{# seconds}} ago' => '{delta, plural, =1{секунду} one{# секунду} few{# секунди} many{# секунд} other{# секунди}} тому',
    '{delta, plural, =1{a year} other{# years}} ago' => '{delta, plural, =1{рік} one{# рік} few{# роки} many{# років} other{# роки}} тому',
    '{delta, plural, =1{an hour} other{# hours}} ago' => '{delta, plural, =1{година} one{# година} few{# години} many{# годин} other{# години}} тому',
    '{nFormatted} B' => '{nFormatted} Б',
    '{nFormatted} GB' => '{nFormatted} Гб',
    '{nFormatted} GiB' => '{nFormatted} ГіБ',
    '{nFormatted} kB' => '{nFormatted} Кб',
    '{nFormatted} KiB' => '{nFormatted} КіБ',
    '{nFormatted} MB' => '{nFormatted} Мб',
    '{nFormatted} MiB' => '{nFormatted} МіБ',
    '{nFormatted} PB' => '{nFormatted} Пб',
    '{nFormatted} PiB' => '{nFormatted} ПіБ',
    '{nFormatted} TB' => '{nFormatted} Тб',
    '{nFormatted} TiB' => '{nFormatted} ТіБ',
    '{nFormatted} {n, plural, =1{byte} other{bytes}}' => '{nFormatted} {n, plural, one{байт} few{байта} many{байтів} other{байта}}',
    '{nFormatted} {n, plural, =1{gibibyte} other{gibibytes}}' => '{nFormatted} {n, plural, one{гібібайт} few{гібібайта} many{гібібайтів} other{гібібайта}}',
    '{nFormatted} {n, plural, =1{gigabyte} other{gigabytes}}' => '{nFormatted} {n, plural, one{гігабайт} few{гігабайта} many{гігабайтів} other{гігабайта}}',
    '{nFormatted} {n, plural, =1{kibibyte} other{kibibytes}}' => '{nFormatted} {n, plural, one{кібібайт} few{кібібайта} many{кібібайтів} other{кібібайта}}',
    '{nFormatted} {n, plural, =1{kilobyte} other{kilobytes}}' => '{nFormatted} {n, plural, one{кілобайт} few{кілобайта} many{кілобайтів} other{кілобайта}}',
    '{nFormatted} {n, plural, =1{mebibyte} other{mebibytes}}' => '{nFormatted} {n, plural, one{мебібайт} few{мебібайта} many{мебібайтів} other{мебібайта}}',
    '{nFormatted} {n, plural, =1{megabyte} other{megabytes}}' => '{nFormatted} {n, plural, one{мегабайт} few{мегабайта} many{мегабайтів} other{мегабайта}}',
    '{nFormatted} {n, plural, =1{pebibyte} other{pebibytes}}' => '{nFormatted} {n, plural, one{пебібайт} few{пебібайта} many{пебібайтів} other{пебібайта}}',
    '{nFormatted} {n, plural, =1{petabyte} other{petabytes}}' => '{nFormatted} {n, plural, one{петабайт} few{петабайта} many{петабайтів} other{петабайта}}',
    '{nFormatted} {n, plural, =1{tebibyte} other{tebibytes}}' => '{nFormatted} {n, plural, one{тебібайт} few{тебібайта} many{тебібайтів} other{тебібайта}}',
    '{nFormatted} {n, plural, =1{terabyte} other{terabytes}}' => '{nFormatted} {n, plural, one{терабайт} few{терабайта} many{терабайтів} other{терабайта}}',
];
