language: php

php:
 - 5.5
 - 5.4

install:
  - composer require --prefer-dist --dev 'codeception/codeception \*' 'codeception/specify \*'

before_script:
  - php vendor/bin/codecept build

script:
  - php vendor/bin/codecept run