build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - "tests/"
    - "build/"
    - "docs/"
    - "framework/messages/"
  dependency_paths:
    - "vendor/"

tools:
    external_code_coverage:
        runs: 3
        timeout: 2100 # Timeout in seconds.
