<?php

namespace yii\captcha\drivers;

use yiiunit\TestCase;
use yii\captcha\drivers\ImageSettings;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-02 at 07:01:49.
 */
class ImageSettingsTest extends TestCase
{
    public function testInitNotKnownFontFileName()
    {
        $this->setExpectedException('yii\base\InvalidConfigException');
        new ImageSettings(['fontFile' => '@yii/captcha/Not_known_font.ttf']);
    }
}
