<?php

declare(strict_types=1);

/**
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

namespace yiiunit\framework\db\pgsql;

use PDO;
use PHPUnit\Framework\Attributes\DataProviderExternal;
use PHPUnit\Framework\Attributes\Group;
use yii\db\ConstraintFinderInterface;
use yii\db\Expression;
use yii\db\pgsql\Schema as PgsqlSchema;
use yii\db\TableSchema;
use yiiunit\data\ar\ActiveRecord;
use yiiunit\data\ar\EnumTypeInCustomSchema;
use yiiunit\data\ar\Type;
use yiiunit\base\db\BaseSchema;
use yiiunit\framework\db\pgsql\providers\SchemaProvider;
use yiiunit\support\DbHelper;

use function fclose;
use function print_r;

/**
 * Unit tests for {@see \yii\db\pgsql\Schema} schema reflection and metadata retrieval for the PostgreSQL driver.
 *
 * {@see SchemaProvider} for test case data providers.
 */
#[Group('db')]
#[Group('pgsql')]
#[Group('schema')]
final class SchemaTest extends BaseSchema
{
    public $driverName = 'pgsql';

    /**
     * @var list<string> List of expected schemas in the database.
     */
    protected array $expectedSchemas = [
        'public',
    ];

    public function testGetPDOType(): void
    {
        $values = [
            [null, PDO::PARAM_NULL],
            ['', PDO::PARAM_STR],
            ['hello', PDO::PARAM_STR],
            [0, PDO::PARAM_INT],
            [1, PDO::PARAM_INT],
            [1337, PDO::PARAM_INT],
            [true, PDO::PARAM_BOOL],
            [false, PDO::PARAM_BOOL],
            [$fp = fopen(__FILE__, 'rb'), PDO::PARAM_LOB],
        ];

        $schema = $this->getConnection()->schema;

        foreach ($values as $value) {
            self::assertSame(
                $value[1],
                $schema->getPdoType($value[0]),
                'PDO type for value ' . print_r($value[0], true) . ' does not match.',
            );
        }

        fclose($fp);
    }

    public function testBooleanDefaultValues(): void
    {
        $schema = $this->getConnection()->schema;

        $table = $schema->getTableSchema('bool_values');

        self::assertTrue(
            $table->getColumn('default_true')->defaultValue,
            "Default must be native 'true'.",
        );
        self::assertFalse(
            $table->getColumn('default_false')->defaultValue,
            "Default must be native 'false'.",
        );
    }

    public function testSequenceName(): void
    {
        $connection = $this->getConnection();

        $sequenceName = $connection->schema->getTableSchema('item')->sequenceName;

        $connection->createCommand(
            <<<SQL
            ALTER TABLE "item" ALTER COLUMN "id" SET DEFAULT nextval('item_id_seq_2')
            SQL
        )->execute();
        $connection->schema->refreshTableSchema('item');

        self::assertSame(
            'item_id_seq_2',
            $connection->schema->getTableSchema('item')->sequenceName,
            'Sequence name must follow the redefined column default.',
        );

        $connection->createCommand(
            <<<SQL
            ALTER TABLE "item" ALTER COLUMN "id" SET DEFAULT nextval('{$sequenceName}')
            SQL
        )->execute();
        $connection->schema->refreshTableSchema('item');

        self::assertSame(
            $sequenceName,
            $connection->schema->getTableSchema('item')->sequenceName,
            'Sequence name must be restored after reverting the default.',
        );
    }

    public function testGeneratedValues(): void
    {
        $table = $this->getConnection()->schema->getTableSchema('generated');

        self::assertTrue(
            $table->getColumn('id_always')->autoIncrement,
            "Column 'GENERATED ALWAYS AS IDENTITY' must be detected as auto-increment via 'attidentity != '''.",
        );
        self::assertTrue(
            $table->getColumn('id_primary')->autoIncrement,
            "Primary key column 'GENERATED ALWAYS AS IDENTITY' must be detected as auto-increment.",
        );
        self::assertTrue(
            $table->getColumn('id_primary')->isPrimaryKey,
            "Primary key column 'GENERATED ALWAYS AS IDENTITY' must be flagged as primary key.",
        );
        self::assertTrue(
            $table->getColumn('id_default')->autoIncrement,
            "Column 'GENERATED BY DEFAULT AS IDENTITY' must be detected as auto-increment.",
        );
    }

    public function testPartitionedTable(): void
    {
        self::assertNotNull(
            $this->getConnection()->schema->getTableSchema('partitioned'),
            "Schema lookup for a 'PARTITION BY RANGE' table must not return 'null'.",
        );
    }

    public function testFindSchemaNames(): void
    {
        $schema = $this->getConnection()->schema;

        self::assertCount(
            3,
            $schema->getSchemaNames(),
            'Number of schema names does not match.',
        );
    }

    public function testGetViewNamesWithDefaultSchema(): void
    {
        $schema = $this->getConnection()->getSchema();

        self::assertInstanceOf(
            PgsqlSchema::class,
            $schema,
            'Schema should support view metadata retrieval.',
        );

        self::assertContains(
            'animal_view',
            $schema->getViewNames(),
            "View 'animal_view' should be present in the default schema.",
        );
    }

    public function testGetTableSchemasWithNonDefaultSchema(): void
    {
        $schema = $this->getConnection()->getSchema();

        $tables = $schema->getTableSchemas('schema1', true);

        self::assertSame(
            $schema->getTableNames('schema1', true),
            array_map(static fn(TableSchema $table): string => $table->name, $tables),
            'Table schemas from a non-default schema should match table names from that schema.',
        );
        self::assertNotEmpty(
            $tables,
            "Schema 'schema1' should contain table schemas.",
        );

        foreach ($tables as $table) {
            self::assertInstanceOf(
                TableSchema::class,
                $table,
                'Table schema should be an instance of ' . TableSchema::class . '.',
            );
            self::assertSame(
                'schema1',
                $table->schemaName,
                'Table schema should keep the non-default schema name.',
            );
            self::assertSame(
                "schema1.{$table->name}",
                $table->fullName,
                'Table schema full name should be prefixed with the non-default schema name.',
            );
        }
    }

    /**
     * @param int|float $bigint Bigint value to test.
     */
    #[DataProviderExternal(SchemaProvider::class, 'bigintValue')]
    public function testBigintValue(int|float $bigint): void
    {
        $this->mockApplication();

        ActiveRecord::$db = $this->getConnection();

        Type::deleteAll();

        $type = new Type();

        $type->setAttributes(
            [
                'bigint_col' => $bigint,
                // whatever just to satisfy NOT NULL columns
                'int_col' => 1,
                'char_col' => 'a',
                'float_col' => 0.1,
                'bool_col' => true,
            ],
            false,
        );
        $type->save(false);

        $actual = Type::find()->one();

        self::assertEquals(
            $bigint,
            $actual->bigint_col,
            'Stored value must roundtrip unchanged.',
        );
    }

    /**
     * @see https://github.com/yiisoft/yii2/issues/12483
     */
    public function testParenthesisDefaultValue(): void
    {
        $db = $this->getConnection(false);

        if ($db->schema->getTableSchema('test_default_parenthesis') !== null) {
            $db->createCommand()->dropTable('test_default_parenthesis')->execute();
        }

        $db->createCommand()->createTable(
            'test_default_parenthesis',
            [
                'id' => 'pk',
                'user_timezone' => 'numeric(5,2) DEFAULT (0)::numeric NOT NULL',
            ],
        )->execute();

        $db->schema->refreshTableSchema('test_default_parenthesis');

        $tableSchema = $db->schema->getTableSchema('test_default_parenthesis');

        self::assertNotNull(
            $tableSchema,
            'Table schema must be loadable.',
        );

        $column = $tableSchema->getColumn('user_timezone');

        self::assertNotNull(
            $column,
            'Column must be present in the table schema.',
        );
        self::assertFalse(
            $column->allowNull,
            'Column must not allow `null`.',
        );
        self::assertSame(
            'numeric',
            $column->dbType,
            "'dbType' does not match.",
        );
        self::assertEquals(
            0,
            $column->defaultValue,
            'Parenthesized default must typecast to its numeric value.',
        );
    }

    /**
     * @see https://github.com/yiisoft/yii2/issues/14192
     */
    public function testTimestampNullDefaultValue(): void
    {
        $db = $this->getConnection(false);

        if ($db->schema->getTableSchema('test_timestamp_default_null') !== null) {
            $db->createCommand()->dropTable('test_timestamp_default_null')->execute();
        }

        $db->createCommand()->createTable(
            'test_timestamp_default_null',
            [
                'id' => 'pk',
                'timestamp' => 'timestamp DEFAULT NULL',
            ],
        )->execute();

        $db->schema->refreshTableSchema('test_timestamp_default_null');

        $tableSchema = $db->schema->getTableSchema('test_timestamp_default_null');

        self::assertNull(
            $tableSchema->getColumn('timestamp')->defaultValue,
            '`DEFAULT NULL` must yield `null`.',
        );
    }

    /**
     * @see https://github.com/yiisoft/yii2/issues/20329
     */
    public function testTimestampUtcNowDefaultValue(): void
    {
        $db = $this->getConnection(false);

        if ($db->schema->getTableSchema('test_timestamp_utc_now_default') !== null) {
            $db->createCommand()->dropTable('test_timestamp_utc_now_default')->execute();
        }

        $db->createCommand()->createTable(
            'test_timestamp_utc_now_default',
            [
                'id' => 'pk',
                'timestamp' => 'timestamp DEFAULT timezone(\'UTC\'::text, now()) NOT NULL',
            ],
        )->execute();

        $db->schema->refreshTableSchema('test_timestamp_utc_now_default');

        $tableSchema = $db->schema->getTableSchema('test_timestamp_utc_now_default');

        self::assertEquals(
            new Expression('timezone(\'UTC\'::text, now())'),
            $tableSchema->getColumn('timestamp')->defaultValue,
            'Default must be preserved as an expression.',
        );
    }

    /**
     * @see https://github.com/yiisoft/yii2/issues/20329
     */
    public function testTimestampNowDefaultValue(): void
    {
        $db = $this->getConnection(false);

        if ($db->schema->getTableSchema('test_timestamp_now_default') !== null) {
            $db->createCommand()->dropTable('test_timestamp_now_default')->execute();
        }

        $db->createCommand()->createTable(
            'test_timestamp_now_default',
            [
                'id' => 'pk',
                'timestamp' => 'timestamp DEFAULT now()',
            ],
        )->execute();

        $db->schema->refreshTableSchema('test_timestamp_now_default');

        $tableSchema = $db->schema->getTableSchema('test_timestamp_now_default');

        self::assertEquals(
            new Expression('now()'),
            $tableSchema->getColumn('timestamp')->defaultValue,
            'Default must be preserved as an expression.',
        );
    }

    /**
     * @see https://github.com/yiisoft/yii2/issues/20329
     */
    public function testTimestampUtcStringDefaultValue(): void
    {
        $db = $this->getConnection(false);

        if ($db->schema->getTableSchema('test_timestamp_utc_string_default') !== null) {
            $db->createCommand()->dropTable('test_timestamp_utc_string_default')->execute();
        }

        $db->createCommand()->createTable(
            'test_timestamp_utc_string_default',
            [
                'id' => 'pk',
                'timestamp' => 'timestamp DEFAULT timezone(\'UTC\'::text, \'1970-01-01 00:00:00+00\'::timestamp with time zone) NOT NULL',
            ],
        )->execute();

        $db->schema->refreshTableSchema('test_timestamp_utc_string_default');

        $tableSchema = $db->schema->getTableSchema('test_timestamp_utc_string_default');

        self::assertEquals(
            new Expression('timezone(\'UTC\'::text, \'1970-01-01 00:00:00+00\'::timestamp with time zone)'),
            $tableSchema->getColumn('timestamp')->defaultValue,
            'Default must be preserved as an expression.',
        );
    }

    public function testCurrentDateDefaultValue(): void
    {
        $db = $this->getConnection(false);

        if ($db->schema->getTableSchema('test_default_current_date') !== null) {
            $db->createCommand()->dropTable('test_default_current_date')->execute();
        }

        $db->createCommand()->createTable(
            'test_default_current_date',
            [
                'id' => 'pk',
                'date_col' => 'date DEFAULT CURRENT_DATE NOT NULL',
            ],
        )->execute();

        $db->schema->refreshTableSchema('test_default_current_date');

        $tableSchema = $db->schema->getTableSchema('test_default_current_date');

        self::assertEquals(
            new Expression('CURRENT_DATE'),
            $tableSchema->getColumn('date_col')->defaultValue,
            "Default must be a 'CURRENT_DATE' expression.",
        );
    }

    public function testCurrentTimeDefaultValue(): void
    {
        $db = $this->getConnection(false);

        if ($db->schema->getTableSchema('test_default_current_time') !== null) {
            $db->createCommand()->dropTable('test_default_current_time')->execute();
        }

        $db->createCommand()->createTable(
            'test_default_current_time',
            [
                'id' => 'pk',
                'time_col' => 'time DEFAULT CURRENT_TIME NOT NULL',
            ],
        )->execute();

        $db->schema->refreshTableSchema('test_default_current_time');

        $tableSchema = $db->schema->getTableSchema('test_default_current_time');

        self::assertEquals(
            new Expression('CURRENT_TIME'),
            $tableSchema->getColumn('time_col')->defaultValue,
            "Default must be a 'CURRENT_TIME' expression.",
        );
    }

    public function testBitDefaultValue(): void
    {
        $db = $this->getConnection(false);

        if ($db->schema->getTableSchema('test_default_bit') !== null) {
            $db->createCommand()->dropTable('test_default_bit')->execute();
        }

        $db->createCommand()->createTable(
            'test_default_bit',
            [
                'id' => 'pk',
                'bit_col' => 'bit(5) DEFAULT B\'10101\' NOT NULL',
            ],
        )->execute();

        $db->schema->refreshTableSchema('test_default_bit');

        $tableSchema = $db->schema->getTableSchema('test_default_bit');

        self::assertSame(
            21,
            $tableSchema->getColumn('bit_col')->defaultValue,
            "Bit literal must decode to its 'integer' value.",
        );
    }

    public function testVarbitDefaultValue(): void
    {
        $db = $this->getConnection(false);

        if ($db->schema->getTableSchema('test_default_varbit') !== null) {
            $db->createCommand()->dropTable('test_default_varbit')->execute();
        }

        $db->createCommand()->createTable(
            'test_default_varbit',
            [
                'id' => 'pk',
                'varbit_col' => 'bit varying(8) DEFAULT B\'101\' NOT NULL',
            ],
        )->execute();

        $db->schema->refreshTableSchema('test_default_varbit');

        $tableSchema = $db->schema->getTableSchema('test_default_varbit');

        self::assertSame(
            5,
            $tableSchema->getColumn('varbit_col')->defaultValue,
            "Bit-varying literal must decode to its 'integer' value.",
        );
    }

    public function testIntegerZeroDefaultValue(): void
    {
        $db = $this->getConnection(false);

        if ($db->schema->getTableSchema('test_default_int_zero') !== null) {
            $db->createCommand()->dropTable('test_default_int_zero')->execute();
        }

        $db->createCommand()->createTable(
            'test_default_int_zero',
            [
                'id' => 'pk',
                'int_col' => 'integer DEFAULT 0 NOT NULL',
            ],
        )->execute();

        $db->schema->refreshTableSchema('test_default_int_zero');

        $tableSchema = $db->schema->getTableSchema('test_default_int_zero');

        self::assertSame(
            0,
            $tableSchema->getColumn('int_col')->defaultValue,
            "Zero default must be typed as 'integer', not a raw string.",
        );
    }

    public function testLoadDefaultExpressionColumn(): void
    {
        $db = $this->getConnection(false);

        $command = $db->createCommand();

        DbHelper::dropTablesIfExist($db, ['default_expression_test']);

        $command->createTable(
            'default_expression_test',
            [
                'int_expression' => 'integer NOT NULL DEFAULT (1 + 2)',
                'text_expression' => "text NOT NULL DEFAULT upper('abc'::text)",
                'jsonb_expression' => 'jsonb NOT NULL DEFAULT jsonb_build_array()',
                'int_literal' => 'integer NOT NULL DEFAULT 42',
                'text_literal' => "varchar(100) NOT NULL DEFAULT 'abc'",
                'jsonb_literal' => 'jsonb NOT NULL DEFAULT \'{"a":1}\'',
                'serial_col' => 'serial',
            ],
        )->execute();

        DbHelper::assertColumnDefaultExpression(
            $db,
            'default_expression_test',
            'int_expression',
            '(1 + 2)',
        );
        DbHelper::assertColumnDefaultExpression(
            $db,
            'default_expression_test',
            'text_expression',
            "upper('abc'::text)",
        );
        DbHelper::assertColumnDefaultExpression(
            $db,
            'default_expression_test',
            'jsonb_expression',
            'jsonb_build_array()',
        );
        DbHelper::assertColumnDefaultValue(
            $db,
            'default_expression_test',
            'int_literal',
            42,
        );
        DbHelper::assertColumnDefaultValue(
            $db,
            'default_expression_test',
            'text_literal',
            'abc',
        );
        DbHelper::assertColumnDefaultValue(
            $db,
            'default_expression_test',
            'jsonb_literal',
            ['a' => 1],
        );
        DbHelper::assertColumnDefaultExpression(
            $db,
            'default_expression_test',
            'serial_col',
            "nextval('default_expression_test_serial_col_seq'::regclass)",
        );

        DbHelper::dropTablesIfExist($db, ['default_expression_test']);
    }

    public function testNonPrimaryKeySequenceDefaultIsPreserved(): void
    {
        $db = $this->getConnection(false);

        DbHelper::dropTablesIfExist($db, ['test_default_nextval']);

        $sql = <<<SQL
        CREATE TABLE {{test_default_nextval}} (id serial PRIMARY KEY, counter_col serial)
        SQL;

        $db->createCommand($sql)->execute();
        $db->schema->refreshTableSchema('test_default_nextval');
        $column = $db->schema->getTableSchema('test_default_nextval')->getColumn('counter_col');

        self::assertTrue(
            $column->autoIncrement,
            'Sequence-backed column must be flagged auto-increment.',
        );
        self::assertInstanceOf(
            Expression::class,
            $column->defaultValue,
            'Default must be an Expression.',
        );
        self::assertSame(
            "nextval('test_default_nextval_counter_col_seq'::regclass)",
            (string) $column->defaultValue,
            'Sequence expression must be preserved.',
        );
    }

    public function testConstraintMetadataWithPdoUppercase(): void
    {
        $db = $this->getConnection(false);

        $pdo = $db->getSlavePdo(true);
        $case = $pdo->getAttribute(PDO::ATTR_CASE);

        try {
            $pdo->setAttribute(PDO::ATTR_CASE, PDO::CASE_UPPER);

            $table = $db->schema->getTableSchema('type', true);

            self::assertArrayHasKey(
                'int_col',
                $table->columns,
                "Column metadata should be normalized when 'PDO::ATTR_CASE' is uppercase.",
            );

            $schema = $db->schema;

            self::assertInstanceOf(
                ConstraintFinderInterface::class,
                $schema,
                'Schema should support constraint metadata retrieval.',
            );

            $foreignKeys = $schema->getTableForeignKeys('composite_fk', true);

            self::assertNotEmpty(
                $foreignKeys,
                'Foreign keys should be reflected when PDO returns uppercase keys.',
            );

            $uniqueIndexes = $db->schema->findUniqueIndexes($db->schema->getTableSchema('T_upsert', true));

            self::assertNotEmpty(
                $uniqueIndexes,
                'Unique indexes should be reflected when PDO returns uppercase keys.',
            );
        } finally {
            $pdo->setAttribute(PDO::ATTR_CASE, $case);
        }
    }

    public function testForeignKeyToNonDefaultSchema(): void
    {
        $table = $this->getConnection()->schema->getTableSchema('fk_to_schema2', true);

        self::assertNotEmpty(
            $table->foreignKeys,
            'Foreign key metadata should be reflected.',
        );

        $foreignKey = reset($table->foreignKeys);

        self::assertSame(
            'schema2.fk_ref',
            $foreignKey[0],
            'Referenced table from a non-default schema should include the schema name.',
        );
    }

    public function testCustomTypeInNonDefaultSchema(): void
    {
        ActiveRecord::$db = $this->getConnection();

        $model = EnumTypeInCustomSchema::find()->one();

        self::assertSame(
            ['VAL2'],
            $model->test_type,
            'Custom enum value must be decoded on read.',
        );

        $model->test_type = ['VAL1'];

        $model->save();

        $modelAfterUpdate = EnumTypeInCustomSchema::find()->one();

        self::assertSame(
            ['VAL1'],
            $modelAfterUpdate->test_type,
            'Updated enum value must roundtrip.',
        );
    }
}
