FROM yiisoftware/yii2-php:7.4-apache

RUN apt-get update
RUN apt-get install -y curl apt-transport-https

RUN apt-get install -y unixodbc unixodbc-dev && pecl install sqlsrv-5.10.1 pdo_sqlsrv-5.10.1
RUN docker-php-ext-enable sqlsrv pdo_sqlsrv

RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
RUN curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | tee /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql17

WORKDIR /project
COPY ./ /project
RUN composer install --prefer-dist
