<?php
/**
 * Plural rules.
 *
 * This file is automatically generated by the "yii locale/plural" command under the "build" folder.
 * Do not modify it directly.
 *
 * The original plural rule data used for generating this file has the following copyright terms:
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @revision 6008 (of the original plural file)
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
return [
  'ar' =>
  [
    0 => '$n==0',
    1 => '$n==1',
    2 => '$n==2',
    3 => 'in_array(fmod($n,100),range(3,10))',
    4 => 'in_array(fmod($n,100),range(11,99))',
  ],
  'asa' =>
  [
    0 => '$n==1',
  ],
  'af' =>
  [
    0 => '$n==1',
  ],
  'bem' =>
  [
    0 => '$n==1',
  ],
  'bez' =>
  [
    0 => '$n==1',
  ],
  'bg' =>
  [
    0 => '$n==1',
  ],
  'bn' =>
  [
    0 => '$n==1',
  ],
  'brx' =>
  [
    0 => '$n==1',
  ],
  'ca' =>
  [
    0 => '$n==1',
  ],
  'cgg' =>
  [
    0 => '$n==1',
  ],
  'chr' =>
  [
    0 => '$n==1',
  ],
  'da' =>
  [
    0 => '$n==1',
  ],
  'de' =>
  [
    0 => '$n==1',
  ],
  'dv' =>
  [
    0 => '$n==1',
  ],
  'ee' =>
  [
    0 => '$n==1',
  ],
  'el' =>
  [
    0 => '$n==1',
  ],
  'en' =>
  [
    0 => '$n==1',
  ],
  'eo' =>
  [
    0 => '$n==1',
  ],
  'es' =>
  [
    0 => '$n==1',
  ],
  'et' =>
  [
    0 => '$n==1',
  ],
  'eu' =>
  [
    0 => '$n==1',
  ],
  'fi' =>
  [
    0 => '$n==1',
  ],
  'fo' =>
  [
    0 => '$n==1',
  ],
  'fur' =>
  [
    0 => '$n==1',
  ],
  'fy' =>
  [
    0 => '$n==1',
  ],
  'gl' =>
  [
    0 => '$n==1',
  ],
  'gsw' =>
  [
    0 => '$n==1',
  ],
  'gu' =>
  [
    0 => '$n==1',
  ],
  'ha' =>
  [
    0 => '$n==1',
  ],
  'haw' =>
  [
    0 => '$n==1',
  ],
  'he' =>
  [
    0 => '$n==1',
  ],
  'is' =>
  [
    0 => '$n==1',
  ],
  'it' =>
  [
    0 => '$n==1',
  ],
  'jmc' =>
  [
    0 => '$n==1',
  ],
  'kaj' =>
  [
    0 => '$n==1',
  ],
  'kcg' =>
  [
    0 => '$n==1',
  ],
  'kk' =>
  [
    0 => '$n==1',
  ],
  'kl' =>
  [
    0 => '$n==1',
  ],
  'ksb' =>
  [
    0 => '$n==1',
  ],
  'ku' =>
  [
    0 => '$n==1',
  ],
  'lb' =>
  [
    0 => '$n==1',
  ],
  'lg' =>
  [
    0 => '$n==1',
  ],
  'mas' =>
  [
    0 => '$n==1',
  ],
  'ml' =>
  [
    0 => '$n==1',
  ],
  'mn' =>
  [
    0 => '$n==1',
  ],
  'mr' =>
  [
    0 => '$n==1',
  ],
  'nah' =>
  [
    0 => '$n==1',
  ],
  'nb' =>
  [
    0 => '$n==1',
  ],
  'nd' =>
  [
    0 => '$n==1',
  ],
  'ne' =>
  [
    0 => '$n==1',
  ],
  'nl' =>
  [
    0 => '$n==1',
  ],
  'nn' =>
  [
    0 => '$n==1',
  ],
  'no' =>
  [
    0 => '$n==1',
  ],
  'nr' =>
  [
    0 => '$n==1',
  ],
  'ny' =>
  [
    0 => '$n==1',
  ],
  'nyn' =>
  [
    0 => '$n==1',
  ],
  'om' =>
  [
    0 => '$n==1',
  ],
  'or' =>
  [
    0 => '$n==1',
  ],
  'pa' =>
  [
    0 => '$n==1',
  ],
  'pap' =>
  [
    0 => '$n==1',
  ],
  'ps' =>
  [
    0 => '$n==1',
  ],
  'pt' =>
  [
    0 => '$n==1',
  ],
  'rof' =>
  [
    0 => '$n==1',
  ],
  'rm' =>
  [
    0 => '$n==1',
  ],
  'rwk' =>
  [
    0 => '$n==1',
  ],
  'saq' =>
  [
    0 => '$n==1',
  ],
  'seh' =>
  [
    0 => '$n==1',
  ],
  'sn' =>
  [
    0 => '$n==1',
  ],
  'so' =>
  [
    0 => '$n==1',
  ],
  'sq' =>
  [
    0 => '$n==1',
  ],
  'ss' =>
  [
    0 => '$n==1',
  ],
  'ssy' =>
  [
    0 => '$n==1',
  ],
  'st' =>
  [
    0 => '$n==1',
  ],
  'sv' =>
  [
    0 => '$n==1',
  ],
  'sw' =>
  [
    0 => '$n==1',
  ],
  'syr' =>
  [
    0 => '$n==1',
  ],
  'ta' =>
  [
    0 => '$n==1',
  ],
  'te' =>
  [
    0 => '$n==1',
  ],
  'teo' =>
  [
    0 => '$n==1',
  ],
  'tig' =>
  [
    0 => '$n==1',
  ],
  'tk' =>
  [
    0 => '$n==1',
  ],
  'tn' =>
  [
    0 => '$n==1',
  ],
  'ts' =>
  [
    0 => '$n==1',
  ],
  'ur' =>
  [
    0 => '$n==1',
  ],
  'wae' =>
  [
    0 => '$n==1',
  ],
  've' =>
  [
    0 => '$n==1',
  ],
  'vun' =>
  [
    0 => '$n==1',
  ],
  'xh' =>
  [
    0 => '$n==1',
  ],
  'xog' =>
  [
    0 => '$n==1',
  ],
  'zu' =>
  [
    0 => '$n==1',
  ],
  'ak' =>
  [
    0 => '($n==0||$n==1)',
  ],
  'am' =>
  [
    0 => '($n==0||$n==1)',
  ],
  'bh' =>
  [
    0 => '($n==0||$n==1)',
  ],
  'fil' =>
  [
    0 => '($n==0||$n==1)',
  ],
  'tl' =>
  [
    0 => '($n==0||$n==1)',
  ],
  'guw' =>
  [
    0 => '($n==0||$n==1)',
  ],
  'hi' =>
  [
    0 => '($n==0||$n==1)',
  ],
  'ln' =>
  [
    0 => '($n==0||$n==1)',
  ],
  'mg' =>
  [
    0 => '($n==0||$n==1)',
  ],
  'nso' =>
  [
    0 => '($n==0||$n==1)',
  ],
  'ti' =>
  [
    0 => '($n==0||$n==1)',
  ],
  'wa' =>
  [
    0 => '($n==0||$n==1)',
  ],
  'ff' =>
  [
    0 => '($n>=0&&$n<=2)&&$n!=2',
  ],
  'fr' =>
  [
    0 => '($n>=0&&$n<=2)&&$n!=2',
  ],
  'kab' =>
  [
    0 => '($n>=0&&$n<=2)&&$n!=2',
  ],
  'lv' =>
  [
    0 => '$n==0',
    1 => 'fmod($n,10)==1&&fmod($n,100)!=11',
  ],
  'iu' =>
  [
    0 => '$n==1',
    1 => '$n==2',
  ],
  'kw' =>
  [
    0 => '$n==1',
    1 => '$n==2',
  ],
  'naq' =>
  [
    0 => '$n==1',
    1 => '$n==2',
  ],
  'se' =>
  [
    0 => '$n==1',
    1 => '$n==2',
  ],
  'sma' =>
  [
    0 => '$n==1',
    1 => '$n==2',
  ],
  'smi' =>
  [
    0 => '$n==1',
    1 => '$n==2',
  ],
  'smj' =>
  [
    0 => '$n==1',
    1 => '$n==2',
  ],
  'smn' =>
  [
    0 => '$n==1',
    1 => '$n==2',
  ],
  'sms' =>
  [
    0 => '$n==1',
    1 => '$n==2',
  ],
  'ga' =>
  [
    0 => '$n==1',
    1 => '$n==2',
    2 => 'in_array($n,array(3,4,5,6))',
    3 => 'in_array($n,array(7,8,9,10))',
  ],
  'ro' =>
  [
    0 => '$n==1',
    1 => '$n==0||$n!=1&&in_array(fmod($n,100),range(1,19))',
  ],
  'mo' =>
  [
    0 => '$n==1',
    1 => '$n==0||$n!=1&&in_array(fmod($n,100),range(1,19))',
  ],
  'lt' =>
  [
    0 => 'fmod($n,10)==1&&!in_array(fmod($n,100),range(11,19))',
    1 => 'in_array(fmod($n,10),range(2,9))&&!in_array(fmod($n,100),range(11,19))',
  ],
  'be' =>
  [
    0 => 'fmod($n,10)==1&&fmod($n,100)!=11',
    1 => 'in_array(fmod($n,10),array(2,3,4))&&!in_array(fmod($n,100),array(12,13,14))',
    2 => 'fmod($n,10)==0||in_array(fmod($n,10),array(5,6,7,8,9))||in_array(fmod($n,100),array(11,12,13,14))',
  ],
  'bs' =>
  [
    0 => 'fmod($n,10)==1&&fmod($n,100)!=11',
    1 => 'in_array(fmod($n,10),array(2,3,4))&&!in_array(fmod($n,100),array(12,13,14))',
    2 => 'fmod($n,10)==0||in_array(fmod($n,10),array(5,6,7,8,9))||in_array(fmod($n,100),array(11,12,13,14))',
  ],
  'hr' =>
  [
    0 => 'fmod($n,10)==1&&fmod($n,100)!=11',
    1 => 'in_array(fmod($n,10),array(2,3,4))&&!in_array(fmod($n,100),array(12,13,14))',
    2 => 'fmod($n,10)==0||in_array(fmod($n,10),array(5,6,7,8,9))||in_array(fmod($n,100),array(11,12,13,14))',
  ],
  'ru' =>
  [
    0 => 'fmod($n,10)==1&&fmod($n,100)!=11',
    1 => 'in_array(fmod($n,10),array(2,3,4))&&!in_array(fmod($n,100),array(12,13,14))',
    2 => 'fmod($n,10)==0||in_array(fmod($n,10),array(5,6,7,8,9))||in_array(fmod($n,100),array(11,12,13,14))',
  ],
  'sh' =>
  [
    0 => 'fmod($n,10)==1&&fmod($n,100)!=11',
    1 => 'in_array(fmod($n,10),array(2,3,4))&&!in_array(fmod($n,100),array(12,13,14))',
    2 => 'fmod($n,10)==0||in_array(fmod($n,10),array(5,6,7,8,9))||in_array(fmod($n,100),array(11,12,13,14))',
  ],
  'sr' =>
  [
    0 => 'fmod($n,10)==1&&fmod($n,100)!=11',
    1 => 'in_array(fmod($n,10),array(2,3,4))&&!in_array(fmod($n,100),array(12,13,14))',
    2 => 'fmod($n,10)==0||in_array(fmod($n,10),array(5,6,7,8,9))||in_array(fmod($n,100),array(11,12,13,14))',
  ],
  'uk' =>
  [
    0 => 'fmod($n,10)==1&&fmod($n,100)!=11',
    1 => 'in_array(fmod($n,10),array(2,3,4))&&!in_array(fmod($n,100),array(12,13,14))',
    2 => 'fmod($n,10)==0||in_array(fmod($n,10),array(5,6,7,8,9))||in_array(fmod($n,100),array(11,12,13,14))',
  ],
  'cs' =>
  [
    0 => '$n==1',
    1 => 'in_array($n,array(2,3,4))',
  ],
  'sk' =>
  [
    0 => '$n==1',
    1 => 'in_array($n,array(2,3,4))',
  ],
  'pl' =>
  [
    0 => '$n==1',
    1 => 'in_array(fmod($n,10),array(2,3,4))&&!in_array(fmod($n,100),array(12,13,14))',
    2 => '$n!=1&&in_array(fmod($n,10),array(0,1))||in_array(fmod($n,10),array(5,6,7,8,9))||in_array(fmod($n,100),array(12,13,14))',
  ],
  'sl' =>
  [
    0 => 'fmod($n,100)==1',
    1 => 'fmod($n,100)==2',
    2 => 'in_array(fmod($n,100),array(3,4))',
  ],
  'mt' =>
  [
    0 => '$n==1',
    1 => '$n==0||in_array(fmod($n,100),range(2,10))',
    2 => 'in_array(fmod($n,100),range(11,19))',
  ],
  'mk' =>
  [
    0 => 'fmod($n,10)==1&&$n!=11',
  ],
  'cy' =>
  [
    0 => '$n==0',
    1 => '$n==1',
    2 => '$n==2',
    3 => '$n==3',
    4 => '$n==6',
  ],
  'lag' =>
  [
    0 => '$n==0',
    1 => '($n>=0&&$n<=2)&&$n!=0&&$n!=2',
  ],
  'shi' =>
  [
    0 => '($n>=0&&$n<=1)',
    1 => 'in_array($n,range(2,10))',
  ],
  'br' =>
  [
    0 => 'fmod($n,10)==1&&!in_array(fmod($n,100),array(11,71,91))',
    1 => 'fmod($n,10)==2&&!in_array(fmod($n,100),array(12,72,92))',
    2 => 'in_array(fmod($n,10),array(3,4,9))&&!in_array(fmod($n,100),array_merge(range(10,19),range(70,79),range(90,99)))',
    3 => 'fmod($n,1000000)==0&&$n!=0',
  ],
  'ksh' =>
  [
    0 => '$n==0',
    1 => '$n==1',
  ],
  'tzm' =>
  [
    0 => '($n==0||$n==1)||in_array($n,range(11,99))',
  ],
  'gv' =>
  [
    0 => 'in_array(fmod($n,10),array(1,2))||fmod($n,20)==0',
  ],
];
