<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '(nav uzstādīts)',
    'An internal server error occurred.' => 'Notika servera iekšēja kļūda.',
    'Delete' => 'Dzēst',
    'Error' => 'Kļūda',
    'File upload failed.' => 'Neizdevās augšupielādēt failu.',
    'Home' => 'Galvenā',
    'Invalid data received for parameter "{param}".' => 'Tika saņemta nepareiza vērtība parametram "{param}".',
    'Login Required' => 'Nepieciešama autorizācija.',
    'Missing required arguments: {params}' => 'Trūkst nepieciešamos argumentus: {params}',
    'Missing required parameters: {params}' => 'Trūkst nepieciešamos parametrus: {params}',
    'No' => 'Nē',
    'No help for unknown command "{command}".' => 'Palīdzība nezināmai komandai "{command}" nav pieejama.',
    'No help for unknown sub-command "{command}".' => 'Palīdzība nezināmai sub-komandai "{command}" nav pieejama',
    'No results found.' => 'Nekas nav atrasts.',
    'Only files with these extensions are allowed: {extensions}.' => 'Ir atļauts augšupielādēt failus tikai ar sekojošiem paplašinājumiem: {extensions}.',
    'Page not found.' => 'Pieprasīta lapa netika atrasta.',
    'Please fix the following errors:' => 'Nepieciešams izlabot sekojošas kļūdas:',
    'Please upload a file.' => 'Lūdzu, augšupielādiet failu.',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.' => 'Tiek rādīti ieraksti <b>{begin, number}-{end, number}</b> no <b>{totalCount, number}</b>.',
    'The file "{file}" is not an image.' => 'Fails „{file}” nav uzskatīts par attēlu.',
    'The file "{file}" is too big. Its size cannot exceed {limit, number} {limit, plural, one{byte} other{bytes}}.' => 'Fails „{file}” pārsniedz pieļaujamo ierobežojumu. Izmēram nedrīkst pārsniegt {limit, number} {limit, plural, one{baitu} few{baitus} many{baitus} other{baitus}}.',
    'The file "{file}" is too small. Its size cannot be smaller than {limit, number} {limit, plural, one{byte} other{bytes}}.' => 'Fails „{file}” ir pārāk mazs. Izmēram ir jābūt vairāk par {limit, number} {limit, plural, one{baitu} few{baitus} many{baitus} other{baitus}}.',
    'The format of {attribute} is invalid.' => 'Vērtībai „{attribute}” ir nepareizs formāts.',
    'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Attēls „{file}” ir pārāk liels. Augstumam ir jābūt mazākam par {limit, number} {limit, plural, one{pikseļi} few{pikseļiem} many{pikseļiem} other{pikseļiem}}.',
    'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Attēls „{file}” ir pārāk liels. Platumam ir jābūt mazākam par {limit, number} {limit, plural, one{pikseļi} few{pikseļiem} many{pikseļiem} other{pikseļiem}}.',
    'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Attēls „{file}” ir pārāk mazs. Augstumam ir jābūt lielākam par {limit, number} {limit, plural, one{pikseļi} few{pikseļiem} many{pikseļiem} other{pikseļiem}}.',
    'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Attēls „{file}” ir pārāk mazs. Platumam ir jābūt lielākam par {limit, number} {limit, plural, one{pikseļi} few{pikseļiem} many{pikseļiem} other{pikseļiem}}.',
    'The verification code is incorrect.' => 'Nepareizs pārbaudes kods.',
    'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.' => 'Kopā <b>{count, number}</b> {count, plural, one{ieraksts} few{ieraksti} many{ieraksti} other{ieraksti}}.',
    'Unable to verify your data submission.' => 'Neizdevās pārbaudīt nosūtītos datus.',
    'Unknown command "{command}".' => 'Nezināma komanda "{command}".',
    'Unknown option: --{name}' => 'Nezināma opcija: --{name}',
    'Update' => 'Labot',
    'View' => 'Skatīties',
    'Yes' => 'Jā',
    'You are not allowed to perform this action.' => 'Jūs neesat autorizēts veikt šo darbību.',
    'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.' => 'Jūs nevarat augšupielādēt vairāk par {limit, number} {limit, plural, one{failu} few{failus} many{failus} other{failus}}.',
    'the input value' => 'ievadīta vērtība',
    '{attribute} "{value}" has already been taken.' => '{attribute} „{value}” jau ir aizņemts.',
    '{attribute} cannot be blank.' => 'Ir jāaizpilda „{attribute}”.',
    '{attribute} is invalid.' => '„{attribute}” vērtība ir nepareiza.',
    '{attribute} is not a valid URL.' => '„{attribute}” vērtība netiek uzskatīta par pareizu URL.',
    '{attribute} is not a valid email address.' => '„{attribute}” vērtība netiek uzskatīta par pareizu e-pasta adresi.',
    '{attribute} must be "{requiredValue}".' => '„{attribute}” vērtībai ir jābūt vienādai ar „{requiredValue}”.',
    '{attribute} must be a number.' => '„{attribute}” vērtībai ir jābūt skaitlim.',
    '{attribute} must be a string.' => '„{attribute}” vērtībai ir jābūt virknei.',
    '{attribute} must be an integer.' => '„{attribute}” vērtībai ir jābūt veselam skaitlim.',
    '{attribute} must be either "{true}" or "{false}".' => '„{attribute}” vērtībai ir jābūt „{true}” vai „{false}”.',
    '{attribute} must be greater than "{compareValue}".' => '„{attribute}” vērtībai ir jābūt lielākai par „{compareValue}” vērību.',
    '{attribute} must be greater than or equal to "{compareValue}".' => '„{attribute}” vērtībai ir jābūt lielākai vai vienādai ar „{compareValue}” vērtību.',
    '{attribute} must be less than "{compareValue}".' => '„{attribute}” vērtībai ir jābūt mazākai par „{compareValue}” vērtību.',
    '{attribute} must be less than or equal to "{compareValue}".' => '„{attribute}” vērtībai ir jābūt mazākai vai vienādai ar „{compareValue}” vērtību.',
    '{attribute} must be no greater than {max}.' => '„{attribute}” vērtībai nedrīkst pārsniegt {max}.',
    '{attribute} must be no less than {min}.' => '„{attribute}” vērtībai ir jāpārsniedz {min}.',
    '{attribute} must be repeated exactly.' => '„{attribute}” vērtībai ir precīzi jāatkārto.',
    '{attribute} must not be equal to "{compareValue}".' => '„{attribute}” vērtībai nedrīkst būt vienādai ar „{compareValue}”.',
    '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => '„{attribute}” vērtībai ir jāietver vismaz {min, number} {min, plural, one{simbolu} few{simbolus} many{simbolus} other{simbolus}}.',
    '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.' => '„{attribute}” vērtībai ir jāietver ne vairāk par {max, number} {max, plural, one{simbolu} few{simbolus} many{simbolus} other{simbolus}}.',
    '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => '„{attribute}” vērtībai ir jāietver {length, number} {length, plural, one{simbolu} few{simbolus} many{simbolus} other{simbolus}}.',
];
