<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '(nu este setat)',
    'An internal server error occurred.' => 'A aparut o eroare internă de server.',
    'Delete' => 'Șterge',
    'Error' => 'Eroare',
    'File upload failed.' => 'Încărcarea fișierului a eșuat.',
    'Home' => 'Acasă',
    'Invalid data received for parameter "{param}".' => 'Date incorecte primite pentru parametrul "{param}".',
    'Login Required' => 'Autentificare obligatorie.',
    'Missing required arguments: {params}' => 'Lipsesc argumente obligatorii: {params}',
    'Missing required parameters: {params}' => 'Lipsesc parametrii obligatori: {params}',
    'No' => 'Nu',
    'No help for unknown command "{command}".' => 'Nu sunt referințe pentru comanda necunoscută "{command}".',
    'No help for unknown sub-command "{command}".' => 'Nu sunt referințe pentru sub-comanda necunoscută "{command}".',
    'No results found.' => 'Nu a fost găsit niciun rezultat.',
    'Only files with these extensions are allowed: {extensions}.' => 'Se acceptă numai fișiere cu următoarele extensii: {extensions}.',
    'Page not found.' => 'Pagina nu a fost găsită.',
    'Please fix the following errors:' => 'Vă rugăm sa corectați următoarele erori:',
    'Please upload a file.' => 'Vă rugăm sa încărcați un fișier.',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.' => 'Sunt afișați itemii <b>{begin, number}-{end, number}</b> din <b>{totalCount, number}</b>.',
    'The file "{file}" is not an image.' => 'Fișierul «{file}» nu este o imagine.',
    'The file "{file}" is too big. Its size cannot exceed {formattedLimit}.' => 'Fișierul «{file}» este prea mare. Dimensiunea acestuia nu trebuie să fie mai mare de {formattedLimit}.',
    'The file "{file}" is too small. Its size cannot be smaller than {formattedLimit}.' => 'Fișierul «{file}» este prea mic. Dimensiunea acestuia nu trebuie sa fie mai mică de {formattedLimit}.',
    'The format of {attribute} is invalid.' => 'Formatul «{attribute}» nu este valid.',
    'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Imaginea «{file}» este prea mare. Înălțimea nu trebuie să fie mai mare de {limit, number} {limit, plural, one{pixel} other{pixeli}}.',
    'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Imaginea «{file}» este prea mare. Lățimea nu trebuie să fie mai mare de {limit, number} {limit, plural, one{pixel} other{pixeli}}.',
    'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Imaginea «{file}» este prea mică. Înălțimea nu trebuie să fie mai mică de {limit, number} {limit, plural, one{pixel} other{pixeli}}.',
    'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Imaginea «{file}» este prea mică. Lățimea nu trebuie sa fie mai mică de {limit, number} {limit, plural, one{pixel} other{pixeli}}.',
    'The verification code is incorrect.' => 'Codul de verificare este incorect.',
    'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.' => 'Total <b>{count, number}</b> {count, plural, one{item} other{itemi}}.',
    'Unable to verify your data submission.' => 'Datele trimise nu au putut fi verificate.',
    'Unknown command "{command}".' => 'Comandă necunoscută "{command}".',
    'Unknown option: --{name}' => 'Opțiune necunoscută : --{name}',
    'Update' => 'Redactare',
    'View' => 'Vizualizare',
    'Yes' => 'Da',
    'You are not allowed to perform this action.' => 'Nu aveți dreptul să efectuați această acțiunea.',
    'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.' => 'Puteți încărca maxim {limit, number} {limit, plural, one{fișier} other{fișiere}}.',
    'the input value' => 'valoarea introdusă',
    '{attribute} "{value}" has already been taken.' => '{attribute} «{value}» este deja ocupat.',
    '{attribute} cannot be blank.' => '«{attribute}» nu poate fi gol.',
    '{attribute} is invalid.' => '«{attribute}» este incorect.',
    '{attribute} is not a valid URL.' => '«{attribute}» nu este un URL valid.',
    '{attribute} is not a valid email address.' => '«{attribute}» nu este o adresă de email validă.',
    '{attribute} must be "{requiredValue}".' => '«{attribute}» trebuie să fie «{requiredValue}».',
    '{attribute} must be a number.' => '«{attribute}» trebuie să fie un număr.',
    '{attribute} must be a string.' => '«{attribute}» trebuie să fie un șir de caractere.',
    '{attribute} must be an integer.' => '«{attribute}» trebuie să fie un număr întreg.',
    '{attribute} must be either "{true}" or "{false}".' => '«{attribute}» trebuie să fie «{true}» sau «{false}».',
    '{attribute} must be greater than "{compareValue}".' => '«{attribute}» trebuie să fie mai mare ca «{compareValue}».',
    '{attribute} must be greater than or equal to "{compareValue}".' => '«{attribute}» trebuie să fie mai mare sau egal cu «{compareValue}».',
    '{attribute} must be less than "{compareValue}".' => '«{attribute}» trebuie să fie mai mic ca «{compareValue}».',
    '{attribute} must be less than or equal to "{compareValue}".' => '«{attribute}» trebuie să fie mai mic sau egal cu «{compareValue}».',
    '{attribute} must be no greater than {max}.' => '«{attribute}» nu trebuie să fie mai mare ca {max}.',
    '{attribute} must be no less than {min}.' => '«{attribute}» nu trebuie să fie mai mic ca {min}.',
    '{attribute} must be repeated exactly.' => '«{attribute}» trebuie să fie repetat exact.',
    '{attribute} must not be equal to "{compareValue}".' => '«{attribute}» nu trebuie să fie egală cu «{compareValue}».',
    '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => '«{attribute}» trebuie să conțină minim {min, number} {min, plural, one{caracter} other{caractere}}.',
    '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.' => '«{attribute}» trebuie să conțină maxim {max, number} {max, plural, one{caracter} other{caractere}}.',
    '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => '«{attribute}» trebuie să conțină {length, number} {length, plural, one{caracter} other{caractere}}.',
];
