<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '(без вредности)',
    'An internal server error occurred.' => 'Дошло је до интерне грешке на среверу.',
    'Delete' => 'Обриши',
    'Error' => 'Грешка',
    'File upload failed.' => 'Постављање фајла није успело.',
    'Home' => 'Почетна',
    'Invalid data received for parameter "{param}".' => 'Неисправан податак добијен у параметру "{param}"',
    'Login Required' => 'Пријава на систем је обавезна',
    'Missing required arguments: {params}' => 'Недостају обавезни аргументи: {params}',
    'Missing required parameters: {params}' => 'Недостају обавезни параметри: {params',
    'No' => 'Не',
    'No help for unknown command "{command}".' => 'Непостоји помоћ за непознату команду "{command}".',
    'No help for unknown sub-command "{command}".' => 'Непостоји помоћ за непознату под-команду "{command}".',
    'No results found.' => 'Нема резултата.',
    'Only files with these extensions are allowed: {extensions}.' => 'Само фајлови са следећим екстензијама су дозвољени: {extensions}.',
    'Page not found.' => 'Страница није пронађена.',
    'Please fix the following errors:' => 'Молимо да исправите следеће грешке:',
    'Please upload a file.' => 'Молимо да поставите фајл.',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.' => 'Приказано <b>{begin, number}-{end, number}</b> од <b>{totalCount, number}</b> {totalCount, plural, 0={ставки} 1={ставке} 2={ставке} 3={ставке} 4={ставке} other{ставки}}.',
    'The file "{file}" is not an image.' => 'Фајл "{file}" није слика.',
    'The file "{file}" is too big. Its size cannot exceed {limit, number} {limit, plural, one{byte} other{bytes}}.' => 'Фајл "{file}" је превелик. Величина не сме бити већа од {limit, number} {limit, plural, one{бајта} few{бајтова} other{бајтова}}.',
    'The file "{file}" is too small. Its size cannot be smaller than {limit, number} {limit, plural, one{byte} other{bytes}}.' => 'Фајл "{file}" је премали. Величина не може бити мања од {limit, number} {limit, plural, one{бајта} few{бајтова} other{бајтова}}.',
    'The format of {attribute} is invalid.' => 'Формат атрибута "{attribute}" је неисправан.',
    'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Слика "{file}" је превелика. Висина не сме бити већа од {limit, number} {limit, plural, one{пиксел} other{пиксела}}.',
    'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Слика "{file}" је превелика. Ширина не сме бити већа од {limit, number} {limit, plural, one{пиксел} other{пиксела}}.',
    'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Слика "{file}" је премала. Висина не сме бити мања од {limit, number} {limit, plural, one{пиксел} other{пиксела}}.',
    'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Слика "{file}" је премала. Ширина не сме бити мања од {limit, number} {limit, plural, one{пиксел} other{пиксела}}.',
    'The verification code is incorrect.' => 'Потврдни код није исправан.',
    'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.' => 'Укупно <b>{count, number}</b> {count, plural, one{ставка} other{ставки}}.',
    'Unable to verify your data submission.' => 'Није могуће верификовати ваше послате податке.',
    'Unknown command "{command}".' => 'Непозната команда "{command}".',
    'Unknown option: --{name}' => 'Непозната опција: --{name}',
    'Update' => 'Исправи',
    'View' => 'Преглед',
    'Yes' => 'Да',
    'You are not allowed to perform this action.' => 'Немате права да извршите ову акцију.',
    'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.' => 'Можете поставити највише {limit, number} {limit, plural, one{фајл} other{фајлова}}.',
    'the input value' => 'улазна вредност',
    '{attribute} "{value}" has already been taken.' => '{attribute} "{value}" је већ заузето.',
    '{attribute} cannot be blank.' => '{attribute} не сме бити празан.',
    '{attribute} is invalid.' => '{attribute} је неисправан.',
    '{attribute} is not a valid URL.' => '{attribute} не садржи исправан URL.',
    '{attribute} is not a valid email address.' => '{attribute} не садржи исправну email адресу.',
    '{attribute} must be "{requiredValue}".' => '{attribute} мора бити "{requiredValue}".',
    '{attribute} must be a number.' => '{attribute} мора бити број.',
    '{attribute} must be a string.' => '{attribute} мора бити текст.',
    '{attribute} must be an integer.' => '{attribute} мора бити цели број.',
    '{attribute} must be either "{true}" or "{false}".' => '{attribute} мора бити "{true}" или "{false}".',
    '{attribute} must be greater than "{compareValue}".' => '{attribute} мора бити већи од "{compareValue}".',
    '{attribute} must be greater than or equal to "{compareValue}".' => '{attribute} мора бити већи или једнак "{compareValue}".',
    '{attribute} must be less than "{compareValue}".' => '{attribute} мора бити мањи од "{compareValue}".',
    '{attribute} must be less than or equal to "{compareValue}".' => '{attribute} мора бити мањи или једнак "{compareValue}".',
    '{attribute} must be no greater than {max}.' => '{attribute} не сме бити већи од "{max}".',
    '{attribute} must be no less than {min}.' => '{attribute} не сме бити мањи од {min}.',
    '{attribute} must be repeated exactly.' => '{attribute} мора бити поновљен исправно.',
    '{attribute} must not be equal to "{compareValue}".' => '{attribute} не сме бити једнак "{compareValue}".',
    '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => '{attribute} мора садржати бар {min, number} {min, plural, one{карактер} other{карактера}}.',
    '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.' => '{attribute} може садржати највише {max, number} {max, plural, one{карактер} other{карактера}}.',
    '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => '{attribute} мора да садржи {length, number} {length, plural, one{карактер} other{карактера}}.',
];
