<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

/**
 * Message translations for Armenian (հայերեն) language.
 * @author Gevorg Mansuryan <gevorgmansuryan@gmail.com>
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'{attribute}\' does not support operator \'{operator}\'.' => '«{attribute}»-ը չի սպասարկում «{operator}» օպերատորը։',
    'Condition for \'{attribute}\' should be either a value or valid operator specification.' => '«{attribute}»-ի համար պետք է լինի արժեք կամ գործող օպերատորի հստակեցում:',
    'Operator \'{operator}\' must be used with search attribute.' => '«{operator}» օպերատորը պետք է օգտագործվի որոնման ատրիբուտի հետ միասին:',
    'Operator \'{operator}\' requires multiple operands.' => '«{operator}» օպերատորը պահանջում բազմակի օպերանդներ։',
    'The format of {filter} is invalid.' => '{filter}-ի ֆորմատը անվավեր է։',
    'Unknown filter attribute \'{attribute}\'' => 'Անհայտ ֆիլտրի ատրիբուտ՝ «{attribute}»։',
];
