#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

require_once __DIR__ . '/../_console_bootstrap.php';

$config = require(__DIR__ . '/_console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
