<?php

declare(strict_types=1);

/**
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

namespace yii\db\oci;

use Generator;
use PDO;
use yii\base\InvalidArgumentException;
use yii\base\NotSupportedException;
use yii\db\Connection;
use yii\db\Exception;
use yii\db\Expression;
use yii\db\PdoValue;
use yii\db\Query;
use yii\helpers\StringHelper;
use yii\db\ExpressionInterface;
use yii\db\TableSchema;

use function array_diff_key;
use function array_flip;
use function array_key_exists;
use function array_keys;
use function count;
use function is_array;
use function is_float;
use function is_string;
use function strlen;
use function substr;

/**
 * QueryBuilder is the query builder for Oracle databases (version 12.1 and above).
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class QueryBuilder extends \yii\db\QueryBuilder
{
    /**
     * Parameter name prefix for the affected-row OUT bind registered by a `BLOB` upsert.
     *
     * {@see Command} detects this prefix to read `SQL%ROWCOUNT` back from the PL/SQL block.
     */
    public const string UPSERT_AFFECTED_PARAM_PREFIX = ':yii_upsert_affected';

    /**
     * @var array mapping from abstract column types (keys) to physical column types (values).
     */
    public $typeMap = [
        Schema::TYPE_PK => 'NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY',
        Schema::TYPE_UPK => 'NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY',
        Schema::TYPE_BIGPK => 'NUMBER(20) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY',
        Schema::TYPE_UBIGPK => 'NUMBER(20) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY',
        Schema::TYPE_CHAR => 'CHAR(1)',
        Schema::TYPE_STRING => 'VARCHAR2(255)',
        Schema::TYPE_TEXT => 'CLOB',
        Schema::TYPE_TINYINT => 'NUMBER(3)',
        Schema::TYPE_SMALLINT => 'NUMBER(5)',
        Schema::TYPE_INTEGER => 'NUMBER(10)',
        Schema::TYPE_BIGINT => 'NUMBER(20)',
        Schema::TYPE_FLOAT => 'NUMBER',
        Schema::TYPE_DOUBLE => 'NUMBER',
        Schema::TYPE_DECIMAL => 'NUMBER',
        Schema::TYPE_DATETIME => 'TIMESTAMP',
        Schema::TYPE_TIMESTAMP => 'TIMESTAMP',
        Schema::TYPE_TIME => 'TIMESTAMP',
        Schema::TYPE_DATE => 'DATE',
        Schema::TYPE_BINARY => 'BLOB',
        Schema::TYPE_BOOLEAN => 'NUMBER(1)',
        Schema::TYPE_MONEY => 'NUMBER(19,4)',
    ];

    /**
     * {@inheritdoc}
     */
    protected function defaultExpressionBuilders()
    {
        return [
            ...parent::defaultExpressionBuilders(),
            \yii\db\conditions\InCondition::class => conditions\InConditionBuilder::class,
            \yii\db\conditions\LikeCondition::class => conditions\LikeConditionBuilder::class,
            LobValue::class => LobValueBuilder::class,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function buildOrderByAndLimit($sql, $orderBy, $limit, $offset)
    {
        $orderBy = $this->buildOrderBy($orderBy);

        if ($orderBy !== '') {
            $sql .= "{$this->separator}{$orderBy}";
        }

        if ($this->hasOffset($offset)) {
            $sql .= "{$this->separator}OFFSET {$offset} ROWS";
        }

        if ($this->hasLimit($limit)) {
            $sql .= "{$this->separator}FETCH NEXT {$limit} ROWS ONLY";
        }

        return $sql;
    }

    /**
     * {@inheritdoc}
     *
     * Oracle does not support the `RECURSIVE` keyword for CTEs. Recursion is implicit when a CTE references itself.
     */
    public function buildWithQueries($withs, &$params)
    {
        if ($withs === null || $withs === []) {
            return '';
        }

        foreach ($withs as $i => $with) {
            $with['recursive'] = false;
            $withs[$i] = $with;
        }

        return parent::buildWithQueries($withs, $params);
    }

    /**
     * Builds a SQL statement for renaming a DB table.
     *
     * @param string $table the table to be renamed. The name will be properly quoted by the method.
     * @param string $newName the new table name. The name will be properly quoted by the method.
     * @return string the SQL statement for renaming a DB table.
     */
    public function renameTable($table, $newName)
    {
        return 'ALTER TABLE ' . $this->db->quoteTableName($table) . ' RENAME TO ' . $this->db->quoteTableName($newName);
    }

    /**
     * Builds a SQL statement for changing the definition of a column.
     *
     * @param string $table the table whose column is to be changed. The table name will be properly quoted by the method.
     * @param string $column the name of the column to be changed. The name will be properly quoted by the method.
     * @param string $type the new column type. The [[getColumnType]] method will be invoked to convert abstract column type (if any)
     * into the physical one. Anything that is not recognized as abstract type will be kept in the generated SQL.
     * For example, 'string' will be turned into 'varchar(255)', while 'string not null' will become 'varchar(255) not null'.
     * @return string the SQL statement for changing the definition of a column.
     */
    public function alterColumn($table, $column, $type)
    {
        $type = $this->getColumnType($type);

        return 'ALTER TABLE ' . $this->db->quoteTableName($table) . ' MODIFY ' . $this->db->quoteColumnName($column) . ' ' . $this->getColumnType($type);
    }

    /**
     * Builds a SQL statement for dropping an index.
     *
     * @param string $name the name of the index to be dropped. The name will be properly quoted by the method.
     * @param string $table the table whose index is to be dropped. The name will be properly quoted by the method.
     * @return string the SQL statement for dropping an index.
     */
    public function dropIndex($name, $table)
    {
        return 'DROP INDEX ' . $this->db->quoteTableName($name);
    }

    /**
     * {@inheritdoc}
     *
     * `IDENTITY` columns reset via `ALTER TABLE ... MODIFY` because system sequences (`ISEQ$$_*`) are not addressable
     * by name.
     *
     * The column's current generation clause is read from the data dictionary and preserved when resetting the
     * identity; Oracle retains the identity options the statement does not specify. User-named sequences use the
     * original `DROP` + `CREATE` recipe.
     */
    public function executeResetSequence($table, $value = null)
    {
        $tableSchema = $this->db->getTableSchema($table);

        if ($tableSchema === null) {
            throw new InvalidArgumentException("Unknown table: $table");
        }

        if ($tableSchema->sequenceName === null) {
            throw new InvalidArgumentException("There is no sequence associated with table: $table");
        }

        if ($value !== null) {
            $value = (int) $value;
        } else {
            if (count($tableSchema->primaryKey) > 1) {
                throw new InvalidArgumentException("Can't reset sequence for composite primary key in table: $table");
            }

            $value = $this->db->useMaster(
                static fn(Connection $db): bool|int|string|null => $db->createCommand(
                    <<<SQL
                    SELECT MAX("{$tableSchema->primaryKey[0]}") FROM "{$tableSchema->name}"
                    SQL
                )->queryScalar(),
            ) + 1;
        }

        if (strncmp($tableSchema->sequenceName, 'ISEQ$$_', 7) === 0) {
            $generationClause = $this->getIdentityGenerationClause($tableSchema);

            $this->db->createCommand(
                <<<SQL
                ALTER TABLE {$this->db->quoteTableName($tableSchema->name)}
                MODIFY ({$this->db->quoteColumnName($tableSchema->primaryKey[0])}
                {$generationClause} AS IDENTITY (START WITH {$value}))
                SQL
            )->execute();

            return;
        }

        $this->db->createCommand(
            <<<SQL
            DROP SEQUENCE "{$tableSchema->sequenceName}"
            SQL
        )->execute();
        $this->db->createCommand(
            <<<SQL
            CREATE SEQUENCE "{$tableSchema->sequenceName}" START WITH {$value} INCREMENT BY 1 NOMAXVALUE NOCACHE
            SQL
        )->execute();
    }

    /**
     * {@inheritdoc}
     */
    public function addForeignKey($name, $table, $columns, $refTable, $refColumns, $delete = null, $update = null)
    {
        $sql = 'ALTER TABLE ' . $this->db->quoteTableName($table)
            . ' ADD CONSTRAINT ' . $this->db->quoteColumnName($name)
            . ' FOREIGN KEY (' . $this->buildColumns($columns) . ')'
            . ' REFERENCES ' . $this->db->quoteTableName($refTable)
            . ' (' . $this->buildColumns($refColumns) . ')';
        if ($delete !== null) {
            $sql .= ' ON DELETE ' . $delete;
        }
        if ($update !== null) {
            throw new Exception('Oracle does not support ON UPDATE clause.');
        }

        return $sql;
    }

    /**
     * {@inheritdoc}
     *
     * Appends the locator `RETURNING` clause required by Oracle `BLOB` values.
     */
    public function insert($table, $columns, &$params)
    {
        return parent::insert($table, $columns, $params)
            . $this->lobReturningClause($this->getLobReturning($params));
    }

    /**
     * {@inheritdoc}
     *
     * The locator protocol supports only a single-row `BLOB` update.
     */
    public function update($table, $columns, $condition, &$params)
    {
        return parent::update($table, $columns, $condition, $params)
            . $this->lobReturningClause($this->getLobReturning($params));
    }

    /**
     * Appends a `RETURNING` clause for the given OUT placeholders, merging any locator clause already present.
     *
     * A DML statement built by {@see insert()} or {@see update()} may already end with a locator `RETURNING`
     * clause; its entries fold into the new clause because Oracle allows a single `RETURNING` clause per statement.
     *
     * @param string $sql DML statement built by this query builder.
     * @param array $params The parameters bound to the SQL statement.
     * @param array<string, string> $placeholders OUT placeholders indexed by unquoted column name.
     *
     * @return string The SQL statement with the merged `RETURNING` clause.
     */
    public function mergeReturning(string $sql, array $params, array $placeholders): string
    {
        $lobPlaceholders = $this->getLobReturning($params);

        if ($lobPlaceholders !== []) {
            $sql = substr($sql, 0, -strlen($this->lobReturningClause($lobPlaceholders)));
        }

        return $sql . $this->lobReturningClause([...$lobPlaceholders, ...$placeholders]);
    }

    /**
     * Returns the locator placeholder of every {@see LobValue} parameter, indexed by unquoted column name.
     *
     * @param array $params The parameters to be checked for `BLOB` values.
     *
     * @return array<string, string> Locator placeholders indexed by column name.
     */
    private function getLobReturning(array $params): array
    {
        $placeholders = [];

        foreach ($params as $placeholder => $value) {
            if ($value instanceof LobValue) {
                $placeholders[$value->getColumnName()] = $placeholder;
            }
        }

        return $placeholders;
    }

    /**
     * {@inheritdoc}
     *
     * A `BLOB` value routes to a single anonymous PL/SQL block through {@see upsertWithLob()}, because Oracle `MERGE`
     * cannot return the LOB locators the payload binds require; every other case builds the regular `MERGE`.
     *
     * @see https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_9016.htm#SQLRF01606
     */
    public function upsert($table, $insertColumns, $updateColumns, &$params)
    {
        $tableSchema = $this->db->getTableSchema($table);

        if ($tableSchema !== null) {
            $insertHasLob = false;
            $updateHasLob = false;

            if (is_array($insertColumns)) {
                [$insertColumns, $insertHasLob] = $this->normalizeLobColumns($tableSchema, $insertColumns);
            }

            if (is_array($updateColumns)) {
                [$updateColumns, $updateHasLob] = $this->normalizeLobColumns($tableSchema, $updateColumns);
            }

            if ($insertHasLob || $updateHasLob) {
                return $this->upsertWithLob($table, $insertColumns, $updateColumns, $params);
            }
        }

        [$uniqueNames, $insertNames, $updateNames] = $this->prepareUpsertColumns(
            $table,
            $insertColumns,
            $updateColumns,
            $constraints,
        );

        if ($uniqueNames === []) {
            return $this->insert($table, $insertColumns, $params);
        }

        if ($updateNames === []) {
            // there are no columns to update
            $updateColumns = false;
        }

        $onCondition = ['or'];

        $quotedTableName = $this->db->quoteTableName($table);

        foreach ($constraints as $constraint) {
            $constraintCondition = ['and'];

            foreach ($constraint->columnNames as $name) {
                $quotedName = $this->db->quoteColumnName($name);

                $constraintCondition[] = "$quotedTableName.$quotedName=\"EXCLUDED\".$quotedName";
            }

            $onCondition[] = $constraintCondition;
        }

        $on = $this->buildCondition($onCondition, $params);
        [, $placeholders, $values, $params] = $this->prepareInsertValues(
            $table,
            $insertColumns,
            $params,
        );

        if ($placeholders !== []) {
            $usingSelectValues = [];

            foreach ($insertNames as $index => $name) {
                $usingSelectValues[$name] = new Expression($placeholders[$index]);
            }

            $usingSubQuery = (new Query())
                ->select($usingSelectValues)
                ->from('DUAL');

            [$usingValues, $params] = $this->build($usingSubQuery, $params);
        }

        $usingSource = $usingValues ?? ltrim($values, ' ');

        $mergeSql = <<<SQL
        MERGE INTO {$quotedTableName} USING ({$usingSource}) "EXCLUDED" ON ({$on})
        SQL;

        $insertValues = [];

        foreach ($insertNames as $name) {
            $quotedName = $this->db->quoteColumnName($name);

            if (strrpos($quotedName, '.') === false) {
                $quotedName = "\"EXCLUDED\".{$quotedName}";
            }

            $insertValues[] = $quotedName;
        }

        $namesList = implode(', ', $insertNames);
        $valuesList = implode(', ', $insertValues);

        $insertSql = <<<SQL
        INSERT ({$namesList}) VALUES ({$valuesList})
        SQL;

        if ($updateColumns === false) {
            return <<<SQL
            {$mergeSql} WHEN NOT MATCHED THEN {$insertSql}
            SQL;
        }

        if ($updateColumns === true) {
            $updateColumns = [];
            foreach ($updateNames as $name) {
                $quotedName = $this->db->quoteColumnName($name);

                if (strrpos($quotedName, '.') === false) {
                    $quotedName = "\"EXCLUDED\".{$quotedName}";
                }

                $updateColumns[$name] = new Expression($quotedName);
            }
        }

        [$updates, $params] = $this->prepareUpdateSets($table, $updateColumns, $params);

        $updateSql = 'UPDATE SET ' . implode(', ', $updates);

        return <<<SQL
        {$mergeSql} WHEN MATCHED THEN {$updateSql} WHEN NOT MATCHED THEN {$insertSql}
        SQL;
    }

    /**
     * Generates a batch INSERT SQL statement.
     *
     * For example,
     *
     * ```
     * $sql = $queryBuilder->batchInsert('user', ['name', 'age'], [
     *     ['Tom', 30],
     *     ['Jane', 20],
     *     ['Linda', 25],
     * ]);
     * ```
     *
     * Note that the values in each row must match the corresponding column names.
     *
     * @param string $table The table that new rows will be inserted into.
     * @param array $columns The column names.
     * @param array|Generator $rows The rows to be batch inserted into the table.
     * @param array $params The parameters to be bound to the batch INSERT SQL statement. This parameter is passed by
     * reference and will be modified by this method.
     *
     * @return string The batch INSERT SQL statement.
     */
    public function batchInsert($table, $columns, $rows, &$params = [])
    {
        if ($rows === []) {
            return '';
        }

        $schema = $this->db->getSchema();

        if (($tableSchema = $schema->getTableSchema($table)) !== null) {
            $columnSchemas = $tableSchema->columns;
        } else {
            $columnSchemas = [];
        }

        $values = [];

        foreach ($rows as $row) {
            if ($row === []) {
                continue;
            }

            $vs = [];

            foreach ($row as $i => $value) {
                if (isset($columns[$i], $columnSchemas[$columns[$i]])) {
                    $value = $columnSchemas[$columns[$i]]->dbTypecast($value);
                }

                if ($value instanceof LobValue) {
                    throw new NotSupportedException(
                        "Oracle does not support 'batchInsert()' with a BLOB value; insert the rows individually.",
                    );
                }

                if (is_string($value)) {
                    $value = $schema->quoteValue($value);
                } elseif (is_float($value)) {
                    // ensure type cast always has . as decimal separator in all locales
                    $value = StringHelper::floatToString($value);
                } elseif ($value === false) {
                    $value = 0;
                } elseif ($value === null) {
                    $value = 'NULL';
                } elseif ($value instanceof ExpressionInterface) {
                    $value = $this->buildExpression($value, $params);
                }

                $vs[] = $value;
            }

            $values[] = implode(', ', $vs);
        }

        if ($values === []) {
            return '';
        }

        foreach ($columns as $i => $name) {
            $columns[$i] = $schema->quoteColumnName($name);
        }

        $tableName = $schema->quoteTableName($table);

        $columnList = $columns === [] ? '' : ' (' . implode(', ', $columns) . ')';
        $sourceRows = implode(' FROM SYS.DUAL UNION ALL SELECT ', $values);

        return <<<SQL
        INSERT INTO {$tableName}{$columnList} SELECT {$sourceRows} FROM SYS.DUAL
        SQL;
    }

    /**
     * {@inheritdoc}
     * @since 2.0.8
     */
    public function selectExists($rawSql)
    {
        return 'SELECT CASE WHEN EXISTS(' . $rawSql . ') THEN 1 ELSE 0 END FROM DUAL';
    }

    /**
     * {@inheritdoc}
     * @since 2.0.8
     */
    public function dropCommentFromColumn($table, $column)
    {
        return 'COMMENT ON COLUMN ' . $this->db->quoteTableName($table) . '.' . $this->db->quoteColumnName($column) . " IS ''";
    }

    /**
     * {@inheritdoc}
     * @since 2.0.8
     */
    public function dropCommentFromTable($table)
    {
        return 'COMMENT ON TABLE ' . $this->db->quoteTableName($table) . " IS ''";
    }

    /**
     * {@inheritdoc}
     */
    protected function prepareInsertValues($table, $columns, $params = [])
    {
        [$names, $placeholders, $values, $params] = parent::prepareInsertValues($table, $columns, $params);

        if (!$columns instanceof Query && $names === []) {
            $tableSchema = $this->db->getSchema()->getTableSchema($table);

            if ($tableSchema !== null) {
                $columns = $tableSchema->primaryKey !== []
                    ? $tableSchema->primaryKey
                    : [reset($tableSchema->columns)->name];

                foreach ($columns as $name) {
                    $names[] = $this->db->quoteColumnName($name);
                    $placeholders[] = 'DEFAULT';
                }
            }
        }
        return [$names, $placeholders, $values, $params];
    }

    /**
     * Builds the SQL tokens and LOB locator placeholders for one upsert branch.
     *
     * A {@see LobValue} binds through {@see LobValueBuilder::bind()}, which returns its locator placeholder
     * explicitly instead of leaving it to be inferred from `$params`.
     *
     * @param array<string, mixed> $columns Column values indexed by column name.
     * @param array $params The parameters to be bound to the SQL statement. This parameter is passed by reference and
     * will be modified by this method.
     *
     * @return array{0: array<string, string>, 1: array<string, string>} SQL tokens and LOB locator placeholders.
     */
    private function buildUpsertLobTokens(array $columns, array &$params): array
    {
        $tokens = [];
        $lobPlaceholders = [];

        foreach ($columns as $name => $value) {
            if ($value instanceof LobValue) {
                [$tokens[$name], $lobPlaceholders[$name]] = LobValueBuilder::bind($value, $params);
            } elseif ($value instanceof ExpressionInterface) {
                $tokens[$name] = $this->buildExpression($value, $params);
            } else {
                $tokens[$name] = $this->bindParam($value, $params);
            }
        }

        return [$tokens, $lobPlaceholders];
    }

    /**
     * Registers the affected-row OUT parameter for a `BLOB` upsert.
     */
    private function bindUpsertAffected(array &$params): string
    {
        $placeholder = self::UPSERT_AFFECTED_PARAM_PREFIX;

        while (array_key_exists($placeholder, $params)) {
            $placeholder .= '_';
        }

        $params[$placeholder] = new PdoValue(
            '',
            PDO::PARAM_STR | PDO::PARAM_INPUT_OUTPUT,
        );

        return $placeholder;
    }

    private function getIdentityGenerationClause(TableSchema $tableSchema): string
    {
        $identity = $this->db->useMaster(
            static fn(Connection $db): array|false => $db->createCommand(
                <<<SQL
                SELECT ITC.GENERATION_TYPE, TC.DEFAULT_ON_NULL
                FROM USER_TAB_IDENTITY_COLS ITC
                    INNER JOIN USER_TAB_COLUMNS TC
                        ON TC.TABLE_NAME = ITC.TABLE_NAME AND TC.COLUMN_NAME = ITC.COLUMN_NAME
                WHERE ITC.TABLE_NAME = :tableName
                SQL,
                [':tableName' => $tableSchema->name],
            )->queryOne(PDO::FETCH_NUM),
        );

        if ($identity === false) {
            throw new InvalidArgumentException(
                "There is no identity column in table: {$tableSchema->name}"
            );
        }

        [$generationType, $defaultOnNull] = $identity;

        return match ($generationType) {
            'ALWAYS' => 'GENERATED ALWAYS',
            'BY DEFAULT' => match ($defaultOnNull) {
                'YES' => 'GENERATED BY DEFAULT ON NULL',
                'NO' => 'GENERATED BY DEFAULT',
                default => throw new InvalidArgumentException(
                    "Unable to determine the identity generation clause for table: {$tableSchema->name}"
                ),
            },
            default => throw new InvalidArgumentException(
                "Unable to determine the identity generation clause for table: {$tableSchema->name}"
            ),
        };
    }

    /**
     * Builds the `RETURNING ... INTO ...` clause for the given placeholders.
     *
     * @param array<string, string> $lobPlaceholders Placeholders indexed by unquoted column name.
     *
     * @return string Clause with a leading space, or an empty string when there are no placeholders.
     */
    private function lobReturningClause(array $lobPlaceholders): string
    {
        if ($lobPlaceholders === []) {
            return '';
        }

        $columns = [];

        foreach (array_keys($lobPlaceholders) as $name) {
            $columns[] = $this->db->quoteColumnName($name);
        }

        $columnList = implode(', ', $columns);
        $placeholderList = implode(', ', $lobPlaceholders);

        return <<<SQL
         RETURNING {$columnList} INTO {$placeholderList}
        SQL;
    }

    /**
     * Normalizes the column values and detects whether they contain an Oracle `BLOB` value.
     *
     * @param TableSchema $tableSchema The table schema.
     * @param array<string, mixed> $columns Column values indexed by column name.
     *
     * @return array{0: array, 1: bool} Typecast columns and whether they contain an Oracle `BLOB` value.
     */
    private function normalizeLobColumns(TableSchema $tableSchema, array $columns): array
    {
        $hasLob = false;

        foreach ($columns as $name => $value) {
            $column = $tableSchema->columns[$name] ?? null;

            if ($column !== null) {
                $value = $column->dbTypecast($value);
                $columns[$name] = $value;
            }

            if ($value instanceof LobValue) {
                $hasLob = true;
            }
        }

        return [$columns, $hasLob];
    }

    /**
     * Builds an `UPDATE`/`INSERT` PL/SQL block because Oracle `MERGE` cannot return LOB locators.
     *
     * A duplicate insert retries the update to handle concurrent upserts. An OUT parameter receives the affected row
     * count because PDO reports the PL/SQL block execution instead.
     *
     * @param string $table Target table.
     * @param array|Query $insertColumns Normalized insert values, or a source query.
     * @param array|bool $updateColumns Normalized update values, or a mode flag.
     * @param array $params Binding parameters, passed by reference.
     *
     * @throws NotSupportedException When the insert values come from a {@see Query}, or when zero or more than one
     * primary-key or unique constraint matches the insert values.
     *
     * @return string PL/SQL block.
     */
    private function upsertWithLob(
        string $table,
        array|Query $insertColumns,
        array|bool $updateColumns,
        array &$params,
    ): string {
        if ($insertColumns instanceof Query) {
            throw new NotSupportedException(
                'Oracle does not support upserting a BLOB value sourced from a query.',
            );
        }

        $constraints = [];

        $this->prepareUpsertColumns($table, $insertColumns, $updateColumns, $constraints);

        if (count($constraints) !== 1) {
            throw new NotSupportedException(
                'Oracle BLOB upsert requires exactly one matching primary-key or unique constraint.',
            );
        }

        [$insertTokens, $insertLobs] = $this->buildUpsertLobTokens($insertColumns, $params);

        if ($updateColumns === true) {
            $excluded = array_flip($constraints[0]->columnNames);
            $updateTokens = array_diff_key($insertTokens, $excluded);
            $updateLobs = array_diff_key($insertLobs, $excluded);
        } elseif (is_array($updateColumns)) {
            [$updateTokens, $updateLobs] = $this->buildUpsertLobTokens($updateColumns, $params);
        } else {
            $updateTokens = [];
            $updateLobs = [];
        }

        $affectedParam = $this->bindUpsertAffected($params);
        $quotedTable = $this->db->quoteTableName($table);

        $insertNames = [];

        foreach (array_keys($insertTokens) as $name) {
            $insertNames[] = $this->db->quoteColumnName($name);
        }

        $columnList = implode(', ', $insertNames);
        $valuesList = implode(', ', $insertTokens);

        $returningClause = $this->lobReturningClause($insertLobs);

        $insertSql = <<<SQL
        INSERT INTO {$quotedTable} ({$columnList}) VALUES ({$valuesList}){$returningClause}
        SQL;

        if ($updateTokens === []) {
            return <<<SQL
            DECLARE
                affected PLS_INTEGER := 0;
            BEGIN
                BEGIN
                    {$insertSql};
                    affected := SQL%ROWCOUNT;
                EXCEPTION
                    WHEN DUP_VAL_ON_INDEX THEN
                        affected := 0;
                END;
                {$affectedParam} := affected;
            END;
            SQL;
        }

        $sets = [];

        foreach ($updateTokens as $name => $token) {
            $sets[] = $this->db->quoteColumnName($name) . ' = ' . $token;
        }

        $condition = [];

        foreach ($constraints[0]->columnNames as $name) {
            $condition[] = $this->db->quoteColumnName($name) . ' = ' . $insertTokens[$name];
        }

        $setClause = implode(', ', $sets);
        $whereClause = implode(' AND ', $condition);

        $returningClause = $this->lobReturningClause($updateLobs);

        $updateSql = <<<SQL
        UPDATE {$quotedTable} SET {$setClause} WHERE {$whereClause}{$returningClause}
        SQL;

        return <<<SQL
        DECLARE
            affected PLS_INTEGER := 0;
        BEGIN
            {$updateSql};
            affected := SQL%ROWCOUNT;
            IF affected = 0 THEN
                BEGIN
                    {$insertSql};
                    affected := SQL%ROWCOUNT;
                EXCEPTION
                    WHEN DUP_VAL_ON_INDEX THEN
                        {$updateSql};
                        affected := SQL%ROWCOUNT;
                        IF affected = 0 THEN
                            RAISE;
                        END IF;
                END;
            END IF;
            {$affectedParam} := affected;
        END;
        SQL;
    }
}
