<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '(bez vrednosti)',
    'An internal server error occurred.' => 'Došlo je do interne greške na serveru.',
    'Delete' => 'Obriši',
    'Error' => 'Greška',
    'File upload failed.' => 'Postavljanje fajla nije uspelo.',
    'Home' => 'Početna',
    'Invalid data received for parameter "{param}".' => 'Neispravan podatak dobijen za parametar "{param}".',
    'Login Required' => 'Prijava na sistem je obavezna',
    'Missing required arguments: {params}' => 'Nedostaju obavezni argumenti: {params}',
    'Missing required parameters: {params}' => 'Nedostaju obavezni parametri: {params}',
    'No' => 'Ne',
    'No help for unknown command "{command}".' => 'Ne postoji pomoć za nepoznatu komandu "{command}".',
    'No help for unknown sub-command "{command}".' => 'Ne postoji pomoć za nepoznatu pod-komandu "{command}".',
    'No results found.' => 'Nema rezultata.',
    'Only files with these extensions are allowed: {extensions}.' => 'Samo fajlovi sa sledećim ekstenzijama su dozvoljeni: {extensions}.',
    'Page not found.' => 'Stranica nije pronađena.',
    'Please fix the following errors:' => 'Molimo vas ispravite sledeće greške:',
    'Please upload a file.' => 'Molimo vas postavite fajl.',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.' => 'Prikazano <b>{begin, number}-{end, number}</b> od <b>{totalCount, number}</b> {totalCount, plural, 0={stavki} 1={stavka} 2={stavke} 3={stavke} 4={stavke} other{stavki}}.',
    'The file "{file}" is not an image.' => 'Fajl "{file}" nije slika.',
    'The file "{file}" is too big. Its size cannot exceed {limit, number} {limit, plural, one{byte} other{bytes}}.' => 'Fajl "{file}" je prevelik. Veličina ne može biti veća od {limit, number} {limit, plural, one{bajt} few{bajta} other{bajtova}}.',
    'The file "{file}" is too small. Its size cannot be smaller than {limit, number} {limit, plural, one{byte} other{bytes}}.' => 'Fajl "{file}" је premali. Veličina ne može biti manja od {limit, number} {limit, plural, one{bajt} few{bajta} other{bajtova}}.',
    'The format of {attribute} is invalid.' => 'Format atributa "{attribute}" je neispravan.',
    'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Slika "{file}" je prevelika. Visina ne sme biti veća od {limit, number} {limit, plural, one{piksel} other{piksela}}.',
    'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Slika "{file}" je prevelika. Širina ne sme biti veća od {limit, number} {limit, plural, one{piksel} other{piksela}}.',
    'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Slika "{file}" je premala. Visina ne sme biti manja od {limit, number} {limit, plural, one{piksel} other{piksela}}.',
    'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Slika "{file}" je premala. Širina ne sme biti manja od {limit, number} {limit, plural, one{piksel} other{piksela}}.',
    'The verification code is incorrect.' => 'Kod za potvrdu nije ispravan.',
    'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.' => 'Ukupno <b>{count, number}</b> {count, plural, one{stavka} other{stavki}}.',
    'Unable to verify your data submission.' => 'Nije moguće verifikovati vaše poslate podatke.',
    'Unknown command "{command}".' => 'Nepoznata komanda "{command}".',
    'Unknown option: --{name}' => 'Nepoznata opcija: --{name}',
    'Update' => 'Ispravi',
    'View' => 'Pregled',
    'Yes' => 'Da',
    'You are not allowed to perform this action.' => 'Nemate prava da izvršite ovu akciju.',
    'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.' => 'Možete postaviti najviše {limit, number} {limit, plural, one{fajl} few{fajla} other{fajlova}}.',
    'the input value' => 'ulazna vrednost',
    '{attribute} "{value}" has already been taken.' => '{attribute} "{value}" je već zauzet.',
    '{attribute} cannot be blank.' => '{attribute} ne sme biti prazan.',
    '{attribute} is invalid.' => '{attribute} je neispravan.',
    '{attribute} is not a valid URL.' => '{attribute} nije ispravan URL.',
    '{attribute} is not a valid email address.' => '{attribute} nije ispravna email adresa.',
    '{attribute} must be "{requiredValue}".' => '{attribute} mora biti "{requiredValue}".',
    '{attribute} must be a number.' => '{attribute} mora biti broj.',
    '{attribute} must be a string.' => '{attribute} mora biti tekst.',
    '{attribute} must be an integer.' => '{attribute} mora biti celi broj.',
    '{attribute} must be either "{true}" or "{false}".' => '{attribute} mora biti "{true}" ili "{false}".',
    '{attribute} must be greater than "{compareValue}".' => '{attribute} mora biti veći od "{compareValue}".',
    '{attribute} must be greater than or equal to "{compareValue}".' => '{attribute} mora biti veći ili jednak "{compareValue}".',
    '{attribute} must be less than "{compareValue}".' => '{attribute} mora biti manji od "{compareValue}".',
    '{attribute} must be less than or equal to "{compareValue}".' => '{attribute} mora biti manji ili jednak "{compareValue}".',
    '{attribute} must be no greater than {max}.' => '{attribute} ne sme biti veći od "{max}".',
    '{attribute} must be no less than {min}.' => '{attribute} ne sme biti manji od {min}.',
    '{attribute} must be repeated exactly.' => '{attribute} mora biti ispravno ponovljen.',
    '{attribute} must not be equal to "{compareValue}".' => '{attribute} ne sme biti jednak "{compareValue}".',
    '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => '{attribute} treba da sadrži bar {min, number} {min, plural, one{karakter} other{karaktera}}.',
    '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.' => '{attribute} treba da sadrži najviše {max, number} {max, plural, one{karakter} other{karaktera}}.',
    '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => '{attribute} treba da sadrži {length, number} {length, plural, one{karakter} other{karaktera}}.',
];
