permissions:
  contents: read

name: build-node

on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".appveyor.yml"
      - ".dockerignore"
      - ".editorconfig"
      - ".git-blame-ignore-revs"
      - ".gitattributes"
      - ".github/CONTRIBUTING.md"
      - ".github/FUNDING.yml"
      - ".github/ISSUE_TEMPLATE.md"
      - ".github/PULL_REQUEST_TEMPLATE.md"
      - ".github/SECURITY.md"
      - ".gitignore"
      - ".gitlab-ci.yml"
      - "code-of-conduct.md"
      - "docs/**"
      - "framework/.gitignore"
      - "framework/.phpstorm.meta.php"
      - "framework/CHANGELOG.md"
      - "framework/LICENSE.md"
      - "framework/README.md"
      - "framework/UPGRADE.md"
      - "framework/UPGRADE-22.md"
      - "LICENSE.md"
      - "README.md"
      - "ROADMAP.md"

  push: *ignore-paths

env:
  DEFAULT_COMPOSER_FLAGS: --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ubuntu-latest

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24]

    steps:

      - name: Checkout.
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          php-version: 8.3
          persist-credentials: false

      - name: Install dependencies.
        run: composer update $DEFAULT_COMPOSER_FLAGS

      - name: Install node.js.
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}

      - name: Tests.
        run: |
          npm ci
          npm audit
          npm run lint
          npm test
