permissions:
  contents: read

name: build-node

on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".appveyor.yml"
      - ".dockerignore"
      - ".editorconfig"
      - ".git-blame-ignore-revs"
      - ".gitattributes"
      - ".github/CONTRIBUTING.md"
      - ".github/FUNDING.yml"
      - ".github/ISSUE_TEMPLATE.md"
      - ".github/PULL_REQUEST_TEMPLATE.md"
      - ".github/SECURITY.md"
      - ".gitignore"
      - ".gitlab-ci.yml"
      - "code-of-conduct.md"
      - "docs/**"
      - "framework/.gitignore"
      - "framework/.phpstorm.meta.php"
      - "framework/CHANGELOG.md"
      - "framework/LICENSE.md"
      - "framework/README.md"
      - "framework/UPGRADE.md"
      - "LICENSE.md"
      - "README.md"
      - "ROADMAP.md"

  push: *ignore-paths

env:
  DEFAULT_COMPOSER_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: NPM 10 on ubuntu-22.04

    runs-on: ubuntu-22.04

    steps:

      - name: Checkout.
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install dependencies.
        run: composer update $DEFAULT_COMPOSER_FLAGS

      - name: Install JQuery `3.6.*@stable` for tests.
        run: composer require "bower-asset/jquery:3.6.*@stable"

      - name: Install node.js.
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 20

      - name: Tests.
        run: |
          npm install
          npm run lint
          npm test
