name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - master
      - main
    paths:
      - '.github/**.yml'
      - '.github/**.yaml'
  pull_request:
    paths:
      - '.github/**.yml'
      - '.github/**.yaml'

permissions:
  actions: read # Required by zizmor when reading workflow metadata through the API.
  contents: read # Required to read workflow files.

jobs:
  zizmor:
    uses: yiisoft/actions/.github/workflows/zizmor.yml@master
