<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '(no establert)',
    'An internal server error occurred.' => 'S\'ha produït un error intern al servidor.',
    'Are you sure you want to delete this item?' => 'Estas segur que vols eliminar aquest element?',
    'Delete' => 'Eliminar',
    'Error' => 'Error',
    'File upload failed.' => 'Ha fallat la pujada del fitxer.',
    'Home' => 'Inici',
    'Invalid data received for parameter "{param}".' => 'S\'han rebut dades errònies pel paràmetre "{param}"',
    'Login Required' => 'Login Requerit',
    'Missing required arguments: {params}' => 'Falten arguments requerits: {params}',
    'Missing required parameters: {params}' => 'Falten paràmetres requerits: {params}',
    'No' => 'No',
    'No help for unknown command "{command}".' => 'No hi ha ajuda per l\'ordre desconeguda "{command}"',
    'No help for unknown sub-command "{command}".' => 'No hi ha ajuda per la sub-ordre desconeguda "{command}"',
    'No results found.' => 'No s\'han trobat resultats.',
    'Only files with these MIME types are allowed: {mimeTypes}.' => 'Només s\'accepten arxius amb els següents tipus MIME: {mimeTypes}.',
    'Only files with these extensions are allowed: {extensions}.' => 'Només s\'accepten arxius amb les seguents extensions: {extensions}',
    'Page not found.' => 'No s\'ha trobat la pàgina.',
    'Please fix the following errors:' => 'Si us plau corregeix els següents errors:',
    'Please upload a file.' => 'Si us plau puja un arxiu.',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.' => 'Mostrant  <b>{begin, number}-{end, number}</b> de <b>{totalCount, number}</b> {totalCount, plural, one{element} other{elements}}.',
    'The file "{file}" is not an image.' => 'L\'arxiu "{file}" no és una imatge.',
    'The file "{file}" is too big. Its size cannot exceed {formattedLimit}.' => 'L\'arxiu "{file}" és massa gran. El seu tamany no pot excedir {formattedLimit}.',
    'The file "{file}" is too small. Its size cannot be smaller than {formattedLimit}.' => 'L\'arxiu "{file}" és massa petit. El seu tamany no pot ser menor que {formattedLimit}.',
    'The format of {attribute} is invalid.' => 'El format de {attribute} és invalid.',
    'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'La imatge "{file}" és massa gran. L\'altura no pot ser major que {limit, number} {limit, plural, one{píxel} other{píxels}}.',
    'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'La imatge "{file}" és massa gran. L\'amplada no pot ser major que  {limit, number} {limit, plural, one{píxel} other{píxels}}.',
    'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'La imatge  "{file}" és massa petita. L\'altura no pot ser menor que {limit, number} {limit, plural, one{píxel} other{píxels}}.',
    'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'La imatge "{file}" és massa petita. L\'amplada no pot ser menor que {limit, number} {limit, plural, one{píxel} other{píxels}}.',
    'The verification code is incorrect.' => 'El codi de verificació és incorrecte.',
    'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.' => 'Total <b>{count, number}</b> {count, plural, one{element} other{elements}}.',
    'Unable to verify your data submission.' => 'No s\'ha pogut verificar les dades enviades.',
    'Unknown command "{command}".' => 'Ordre desconeguda "{command}".',
    'Unknown option: --{name}' => 'Opció desconeguda: --{name}',
    'Update' => 'Actualitzar',
    'View' => 'Veure',
    'Yes' => 'Sí',
    'You are not allowed to perform this action.' => 'No tems permís per executar aquesta acció.',
    'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.' => 'Pots pujar com a màxim {limit, number} {limit, plural, one{arxiu} other{arxius}}.',
    'in {delta, plural, =1{a day} other{# days}}' => 'en {delta, plural, =1{un dia} other{# dies}}',
    'in {delta, plural, =1{a minute} other{# minutes}}' => 'en {delta, plural, =1{un minut} other{# minuts}}',
    'in {delta, plural, =1{a month} other{# months}}' => 'en {delta, plural, =1{un mes} other{# mesos}}',
    'in {delta, plural, =1{a second} other{# seconds}}' => 'en {delta, plural, =1{un segon} other{# segons}}',
    'in {delta, plural, =1{a year} other{# years}}' => 'en {delta, plural, =1{un any} other{# anys}}',
    'in {delta, plural, =1{an hour} other{# hours}}' => 'en {delta, plural, =1{una hora} other{# hores}}',
    'the input value' => 'el valor d\'entrada',
    '{attribute} "{value}" has already been taken.' => '{attribute} "{value}" ja ha sigut utilitzat.',
    '{attribute} cannot be blank.' => '{attribute} no pot estar buit.',
    '{attribute} is invalid.' => '{attribute} és invalid.',
    '{attribute} is not a valid URL.' => '{attribute} no és una URL valida.',
    '{attribute} is not a valid email address.' => '{attribute} no es una direcció de correu valida.',
    '{attribute} must be "{requiredValue}".' => '{attribute} ha de ser "{requiredValue}".',
    '{attribute} must be a number.' => '{attribute} ha de  ser un nombre.',
    '{attribute} must be a string.' => '{attribute} ha de ser una cadena de caràcters.',
    '{attribute} must be an integer.' => '{attribute} ha de ser un nombre enter.',
    '{attribute} must be either "{true}" or "{false}".' => '{attribute} ha de ser "{true}" o "{false}".',
    '{attribute} must be greater than "{compareValue}".' => '{attribute} ha de ser major que "{compareValue}',
    '{attribute} must be greater than or equal to "{compareValue}".' => '{attribute} ha de ser major o igual que "{compareValue}".',
    '{attribute} must be less than "{compareValue}".' => '{attribute} ha de ser menor que "{compareValue}".',
    '{attribute} must be less than or equal to "{compareValue}".' => '{attribute} ha de ser menor o igual que "{compareValue}".',
    '{attribute} must be no greater than {max}.' => '{attribute} no pot ser major que {max}.',
    '{attribute} must be no less than {min}.' => '{attribute} no pot ser menor que {min}.',
    '{attribute} must be repeated exactly.' => '{attribute} ha de ser repetit exactament igual.',
    '{attribute} must not be equal to "{compareValue}".' => '{attribute} no pot ser igual que "{compareValue}".',
    '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => '{attribute} hauria de contenir com a mínim {min, number} {min, plural, one{lletra} other{lletres}}.',
    '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.' => '{attribute} hauria de contenir com a màxim {max, number} {max, plural, one{lletra} other{lletres}}.',
    '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => '{attribute} hauria contenir {length, number} {length, plural, one{lletra} other{lletres}}.',
    '{delta, plural, =1{a day} other{# days}} ago' => 'hace {delta, plural, =1{un dia} other{# dies}}',
    '{delta, plural, =1{a minute} other{# minutes}} ago' => 'fa {delta, plural, =1{un minut} other{# minuts}}',
    '{delta, plural, =1{a month} other{# months}} ago' => 'fa {delta, plural, =1{un mes} other{# mesos}}',
    '{delta, plural, =1{a second} other{# seconds}} ago' => 'fa {delta, plural, =1{un segon} other{# segons}}',
    '{delta, plural, =1{a year} other{# years}} ago' => 'fa {delta, plural, =1{un any} other{# anys}}',
    '{delta, plural, =1{an hour} other{# hours}} ago' => 'fa {delta, plural, =1{una hora} other{# hores}}',
    '{n, plural, =1{# byte} other{# bytes}}' => '{n, plural, =1{# byte} other{# bytes}}',
    '{n, plural, =1{# gigabyte} other{# gigabytes}}' => '{n, plural, =1{# gigabyte} other{# gigabytes}}',
    '{n, plural, =1{# kilobyte} other{# kilobytes}}' => '{n, plural, =1{# kilobyte} other{# kilobytes}}',
    '{n, plural, =1{# megabyte} other{# megabytes}}' => '{n, plural, =1{# megabyte} other{# megabytes}}',
    '{n, plural, =1{# petabyte} other{# petabytes}}' => '{n, plural, =1{# petabyte} other{# petabytes}}',
    '{n, plural, =1{# terabyte} other{# terabytes}}' => '{n, plural, =1{# terabyte} other{# terabytes}}',
    '{n} B' => '{n} B',
    '{n} GB' => '{n} GB',
    '{n} KB' => '{n} KB',
    '{n} MB' => '{n} MB',
    '{n} PB' => '{n} PB',
    '{n} TB' => '{n} TB',
];
